### ISSUE TITLE
CTD - Steam can't create game folder

### ISSUE THREAD

**Issue by Mirnaia** [larsiusprime/tdrpg-bugs#1044] opened 2016-06-15 10:55 UTC
Hi!

Operating System: Windows 7 64-bit
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : DX

STEPS TO REPRODUCE:

1. Download the game client to Steam.
2. Have an "á" in your username. Mine is my name, Barabás Frigyes (Barabás is the surname btw)
3. Try to launch the game. CTD.
Screenshot: 
[http://image.prntscr.com/image/0ea6946f434341be9f0ad6b02f3e99ad.png](http://image.prntscr.com/image/0ea6946f434341be9f0ad6b02f3e99ad.png)

WHAT I EXPECTED TO HAPPEN:

That the game doesn't crash into Hell and beyond.

WHAT HAPPENED INSTEAD:

The game crashed into Hell and beyond because it couldn't create a folder. If you press OK on the screenshotthe game quits.

**Comment by IBwWG** [comment] 2016-06-15 11:00
Duplicate of #1042

**Closed by IBwWG** 2016-06-15 11:00 UTC
