### ISSUE TITLE
Bouncer can make the enemies immortal after using the KNOCK BACK effect and hitting again midair.

### ISSUE THREAD

**Issue by PSebs** [larsiusprime/tdrpg-bugs#1633] opened 2019-10-18 00:26 UTC
### Steps to reproduce
Stats used:
Bouncer's level is 9
Shove ability only has damaged maxed out in the skill tree. Everything else in the skill tree is untouched.

1. Start up a level from the world map. Preferably Level 4 Advanced.
2. Pause the game time.
3. Place Bouncer in a spot that's is the closest to the enemy spawn.
4. Disable all of Bouncer's abilities.
5. Turn on BULLDOG mode for bouncer.
6. Boost Bouncer up to level 3 or above.
7. Make bouncer use the cheapest abilities first.
8. Start the game time.
9. At some point when an enemy enters bouncer's range. Pause time and enable Bounce and Shove abilities, then start time again.

### What I expected

The enemies should've died from the powerful Shove attack during KNOCK BACK.

### What actually happened
The enemies somehow survived the hit during KNOCK BACK and ended up at 1 HP. Not only that, the enemies can't be killed from anything. Even Slak, Sword of Swords cannot kill the enemies despite fact that the enemies health is below 5%. 

![20191017191056_1](https://user-images.githubusercontent.com/21015833/67056898-cf884e00-f113-11e9-9529-d8fadaf3e0fa.jpg)

------------------
Manjaro 64 bit
Universal 0.0.4 Linux Build
AMD Ryzen 2500U with Vega 8 Mobile Graphics

**Comment by larsiusprime** [comment] 2019-10-18 02:45
Now that's a heck of a bug! Thanks for finding this.

**Comment by larsiusprime** [comment] 2019-10-18 15:37
Fixed in 0.0.5!

The bug was caused by a weird interaction between PUSH_BACK and KNOCK_BACK where one could override the other. You see, an enemy that is "killed" in the middle of a knock back isn't killed for real until it completes the knock back. What was happening was that if a knocked-back enemy scheduled for death was then *pushed back* before the knock-back ended, it would cancel the knock back and start a push back, but keep it in the "marked for death" state, but still waiting for the knock back to end.

Now I've just set it up so that push back can't interrupt knock back and vice versa, they'll just get added to the priority stack and wait for the previous one to complete (so pushing back a knocked back enemy mid flight will make it wait for a landing and then it'll start the linear shove, and vice versa).

**Closed as completed by larsiusprime** 2019-10-18 15:37 UTC
Labels: bug, DQ2, Battle, 1
