### ISSUE TITLE
Explosive Start + Explosive End = Null Object Reference

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#822] opened 2016-06-02 05:46 UTC
Seems both of these books don't work well together, for some reason, but they do independantly.

Summon a healer in the Night of the Living Knights, watch the explosion. Let the big bloaty blue guys kill it, Null Object Reference when Explosion 2 tries to happen.

**Comment by dqhol** [comment] 2016-06-02 06:17
I had it happen in a battle with just Explosive End equipped. It seems like once an explosion has happened, any explosion, Explosive End trying to trigger will crash the game.

**Comment by larsiusprime** [comment] 2016-06-02 17:30
great report!

**Comment by larsiusprime** [comment] 2016-06-02 17:38
What version of the game? I haven't had it reproduced just yet but it might be kind of infrequent, want to make sure I'm on the same version as you.

**Comment by larsiusprime** [comment] 2016-06-02 18:04
Reproduced, fixed. It happens at x16 speed reliably -- the problem is the trigger delay was keyed to real time, not game time, and so the explosion happens after the defender is gone which screws up the explosion that needs the defender's information to know where to draw the explosion.

**Comment by larsiusprime** [comment] 2016-06-02 18:04
Fixed in 0.8.2

**Closed** 2016-06-02 18:04 UTC
Labels: 1, Battle, bug, DQ CORE, Priority HIGH
