### ISSUE TITLE
Battle UI "dances"

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1654] opened 2019-11-24 14:28 UTC
![DQ2-dancing-UI](https://user-images.githubusercontent.com/26723818/69496096-9e4b2c80-0ece-11ea-93a7-34e8f1ccacfb.gif)

1. Level 11 on Normal
2. Place a Collector in the middle and boost them to Level 4
3. Keep them selected and watch the UI (on any speed)

- Also happens to Eliminators but only one dance and that's it, it seems.
- Doesn't happen to Jumpers.
- Seems to have something to do with interacting with enemies.  Try it on Level 9 and put the defender far from the first enemy.  The UI only dances once they get near enough to engage in battle.
- Happens in both full-screen and windowed mode.

* * *

DQ2 Universal 0.0.5 native on Linux Mint 19 (64-bit) in full-screen mode on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by codingthat** [comment] 2019-12-29 09:42
Also present on latest.
* * *

DQ2 Universal 0.0.6 native on Linux Mint 19 (64-bit) in full-screen mode on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by larsiusprime** [comment] 2019-12-31 15:42
It looks like it occurs when the status effect expires (inspire, in this case, which it saves up unless there's enemies in range).

Likely it's caused by the UI refreshing to remove the status effect, and it unnecessarily repaints the targeting buttons.

**Comment by larsiusprime** [comment] 2019-12-31 16:30
Found a simple fix for it in the button logic. Setting position on a button now only causes it's label to update position (causing a 1-frame "hop") when the new position doesn't match the existing position. TL;DR, it's fixed in 0.0.7

**Closed as completed by larsiusprime** 2019-12-31 16:30 UTC
Labels: bug, DQ2, Battle, 1
