### ISSUE TITLE
Camera jumps back to Azra when moving on the overworld.

### ISSUE THREAD

**Issue by xfullmetal17** [larsiusprime/tdrpg-bugs#881] opened 2016-06-05 01:31 UTC
In the original game, the camera would start moving from wherever it was and track Azra that way. In DQDX it jumps to center on Azra and tracks her from there.  Doesn't change anything gameplay-wise really, just quite jarring.

edit: Version 0.8.4- according to the menu, I grabbed Build 1.

**Comment by ManDude** [comment] 2016-06-05 01:43
Duplicate of #689. ;)

**Closed** 2016-06-08 16:08 UTC
Labels: duplicate
