### ISSUE TITLE
Weird Skull display

### ISSUE THREAD

**Issue by twc1990** [larsiusprime/tdrpg-bugs#1162] opened 2016-07-01 05:31 UTC
Windows 7, Steam DQ1 2.0.6 a

**Steps to Reproduce**
1: In new game plus, get some skulls(I had many stone, a few bronze, and no obsidian)
2: Buy all of the stone skull versions upgrades for a category( swords, bows, staffs)

What Happened: The number of stone skulls you have disappears, and the bronze skull position moves right. If you haven't bought all of the stone upgrades for another category the stone skull stuff appears on top of the bronze skulls(in this case, I still have staff upgrades). This remains if you exit the hermitage and come back.

I'm not sure if this is just this build, or if it exists in previous ones: I've only bought out the upgrades in this build.

![skullplacement](https://cloud.githubusercontent.com/assets/5121380/16512647/8563c22a-3f2b-11e6-90e3-4cb3094c6e58.JPG)

![skullbug](https://cloud.githubusercontent.com/assets/5121380/16512571/c9b88600-3f2a-11e6-8f25-5e759e8f9586.JPG)

Edit: This will occur again if you buy all of the bronze upgrades for a category, collapsing everything rightward.

**Comment by ManDude** [comment] 2016-07-01 13:05
I think this is intended behavior. It only shows the skulls that you need.

**Comment by twc1990** [comment] 2016-07-01 14:56
That's not what I'm talking about. The display works fine for the category where you've bought all of the stone or all of the stone and Bronze upgrades. The issue is if you move to a category where you haven't. Because then the displays start overlapping: look at the second picture, where the stone and Bronze skull displays overlap to the point where you can't read the number of bronze skulls that I have, and the stone skull display looks off (you can see the two  behind the number 1). 

Currently it's worse, in that if I look at the staffs panel, the Bronze and Obsidian skulls are both obscured by the stone skulls.

**Comment by larsiusprime** [comment] 2016-07-01 15:13
Yup, I see the bug.

On Fri, Jul 1, 2016 at 9:56 AM, twc1990 <notifications@github.com> wrote:

> That's not what I'm talking about. The display works fine for the category
> where you've bought all of the stone or all of the stone and Bronze
> upgrades. The issue is if you move to a category where you haven't. Because
> then the displays start overlapping: look at the second picture, where the
> stone and Bronze skull displays overlap to the point where you can't read
> the number of bronze skulls that I have, and the stone skull display looks
> off (you can see the two behind the number 1).
>
> Currently it's worse, in that if I look at the staffs panel, the Bronze
> and Obsidian skulls are both obscured by the stone skulls.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1162#issuecomment-229968574>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-IC1n-HpH__S2s78zpVOYfcdFFbfks5qRSqggaJpZM4JC1J8>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment] 2016-07-01 15:14
Oh I see now. I didn't notice the overlap before. Maybe it should just show all skull types regardless of what is available for sale.

**Comment by larsiusprime** [comment] 2016-07-07 18:43
Fixed in 2.0.7

**Closed by larsiusprime** 2016-07-07 18:43 UTC
Labels: 1, bug, DQ CORE, Priority LOW, Town
