### ISSUE TITLE
Blank square where dragon should be when placed, on non-HD

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#721] opened 2016-04-29 19:11 UTC
While still full-screen 1920x1080, non-HD on the HD edition 0.5.7, the first level you have a dragon available (on normal), I went to place a dragon just now after a few waves were already on screen, and his sprite is completely black, with the "anonymous mask" and lightning, and one enemy but not another showing on top of the black.  Also when I select him (still paused)--radius highlights on top of black.  Boosting, the boost meter also appears, still black.  Deselecting, still black.  Unpausing, still black (hmm.)  Fireball appears on top of the black.

Actually this is also exhibiting bug #716 right now.

Um...attaching my export, but if it gets rid of the layout when you go to the title screen, I'm not sure how it should have the layout.  Oh...but it does seem to, I guess you invalidate it later.  Anyway it was 6 bezerkers in a cluster hardly near the road at all (unlike the export...because I had moved them for the slowness testing), and one dragon near Azra, after the third wave began.

[export-azra-damage-off-blank-dragon.zip](https://github.com/larsiusprime/tdrpg-bugs/files/243060/export-azra-damage-off-blank-dragon.zip)

Dragon blank was reproducible just now.  Also she's invisible while placing (but not black.)

Still exhibiting #716, with health bar jumping all over the place each frame.  She even died just now (for some reason it didn't trigger #719?) and still had a full health bar in the sidebar.

**Comment by larsiusprime** [comment] 2016-05-02 16:45
Is this a generic dragon, for the record? IE, not Niru?

**Comment by IBwWG** [comment] 2016-05-02 16:52
I think it was Niru.

**Comment by larsiusprime** [comment] 2016-05-02 17:04
Okay, so that rules out a bug with custom user colorization, which thankfully indicates a simpler kind of bug to fix.

**Comment by larsiusprime** [comment] 2016-05-02 20:20
Also, FYI: battle layouts are tied to the save slot, and are only invalidated when you go to a different map+difficulty combination, or if you choose to not use a saved layout when prompted.

**Comment by larsiusprime** [comment] 2016-05-03 19:28
In 0.6.2 is this reproducible still? I can't reproduce it myself; I wonder if it's a result of low memory, and fixing the memory leak made it go away? Maybe?

I'll upload 0.6.2 now.

**Comment by IBwWG** [comment] 2016-05-03 19:29
I wonder that too.  Also the haxeflixel logo in that other issue.

**Comment by larsiusprime** [comment] 2016-05-03 19:31
By the way, what's your email address so I can contact you off-github?

On Tue, May 3, 2016 at 2:29 PM, IBwWG <notifications@github.com> wrote:

> I wonder that too. Also the haxeflixel logo in that other issue.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/721#issuecomment-216639532>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment] 2016-05-03 19:55
Sent you a gmail :)

**Comment by larsiusprime** [comment] 2016-05-09 20:28
Closing this for now as it doesn't seem to have been reproduced

**Closed by larsiusprime** 2016-05-09 20:28 UTC
Labels: 1, Battle, bug, DQ CORE, Priority HIGH

**Comment by IBwWG** [comment] 2016-06-05 18:54
0.8.4, win7x64, HD mode@1704x960windowed

I reproduced it just now, but it's actually black boxes all over the place, randomly, and graphics randomly either transparent or black.  But this is definitely a low-memory context (1.4GB + taken up.)
![dq-mem-limit](https://cloud.githubusercontent.com/assets/16719964/15807480/9b656932-2b5f-11e6-930c-7bd0b3089ec0.png)

**Comment by IBwWG** [comment] 2016-06-05 18:55
An interesting side effect, I just saw "NOM" near one of the knights in the centre as they fought.  Probably a mis-matched sprite?

**Comment by IBwWG** [comment] 2016-06-05 18:56
Dang, right on the last wave, crashed for good this time.
