### ISSUE TITLE
Infinite black screen, not a crash, when beating the final battle with Zelemir dead.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#964] opened 2016-06-09 06:26 UTC
Settings: New cutscenes, original sprites, lowest Wide resolution.

Went into battle, got Zelemir killed, pressed F2 to  auto-win. Infinite black screen. Closed game, reopened it, final cutscene played but with no credits after it.

Cutscene plays as Normal on Perfect++ and with Zelemir wounded.

**Comment by larsiusprime** [comment] 2016-06-09 18:39
Yup, reproduced, happens with new sprites too and 4x3 resolution. Looks like it gets caught in an infinite loop constantly trying to show that cutscene.

**Comment by larsiusprime** [comment] 2016-06-09 18:41
@dqhol BTW, I added you (and @mandude and @IBwWG) as collaborators, so you should now be able to apply labels and milestones to bugs yourselves if you want.

Anything that's a bug should get "bug"
By default a regular old bug should also have the "1" label for 1 point
"DQ CORE" is for anything that smells like an engine feature
"DQ1" is for anything that seems like a purely data problem specific to DQ1 only
And then feel free to tag with anything more specific like "Battle" or "Cutscene," etc.

"Alpha" is the milestone for engine bugs, "DQ1 Port" for stuff only specific to DQ1.

Extra tagging is purely optional, but saves me some time and helps me focus on fixing the stuff & makes it easier to triage :D

**Comment by larsiusprime** [comment] 2016-06-09 21:29
Fixed in 0.9.4

**Closed by larsiusprime** 2016-06-09 21:29 UTC
Labels: 1, bug, DQ CORE
