### ISSUE TITLE
Scaling Error

### ISSUE THREAD

**Issue by KipiGiD** [larsiusprime/tdrpg-bugs#1037] opened 2016-06-14 22:16 UTC
When I try to change the game to use fullscreen mode, I get following error:

"Error! Scale must be positive &> 0! (Scale was = 0)"

After I click OK the game crashes. So basically, I'm stuck with 800*600 Windowed mode

I'm using Lenovo Y510P laptop with native resolution of 1920*1080. My OS is Windows 8.1

**Comment by KipiGiD** [comment] 2016-06-14 22:17
Forgot to add, I'm using the latest Steam full version.

**Comment by ManDude** [comment] 2016-06-15 00:26
Duplicate of #1036 .

**Closed by ManDude** 2016-06-15 00:26 UTC
Labels: duplicate
