### ISSUE TITLE
Poison drop from enemy status frame migrates

### ISSUE THREAD

**Issue by JohnKossa** [larsiusprime/tdrpg-bugs#1370] opened 2018-02-14 02:34 UTC
The poison droplet from the enemy status screen has a tendency to "wander" as the enemy moves. I don't have very good steps to reproduce it perfectly yet, but I've seen it happen multiple times and I managed to catch 2 examples in the act.

OS: Windows 7
Game: DX
Version: 2.2.2
Other Information: I'm running the game in fullscreen mode on the left monitor of a 2 monitor setup.

Steps to reproduce:
1. Start a level (It's happened on multiple levels)
2. Set your characters to produce a lot of poison effects
3. Turn game speed up to about 4x (might not be necessary, but this is what made it happen for me)
4. Click various enemies to open their status in the right section.

Expected results:
Poison droplet animation is in its usual place, centered and near the top. If a bleed is present, poison drop shifts left and blood drop pops in on the right.

What actually happens:
The poison droplet occasionally "walks around", sometimes leaving the container entirely. Note: I paused the game to take the screenshot, but I had been previously running it at 4x speed.

![dq2_floating_poison_drop_2](https://user-images.githubusercontent.com/11208054/36184920-2943f20e-10fc-11e8-827a-342c4567c43b.png)
Here you can see the droplet out of position.

![dq2_floating_poison_drop_3](https://user-images.githubusercontent.com/11208054/36184922-33b619c4-10fc-11e8-8466-89f3c1514a5b.png)
Here is is a few game cycles later.

![dq2_floating_poison_drop_4](https://user-images.githubusercontent.com/11208054/36184925-3b425af4-10fc-11e8-9270-e18136a37622.png)
Here is is a few more game cycles later.

The screenshots show the droplet moving down, but that behavior isn't deterministic as far as I can tell. I've also seen them moving left or right before. I have no idea how it chooses which direction. Here's a screencap of the droplet WAY off to the left side. I wish I had caught this one earlier in the process as this one managed to leave its frame entirely. Note that it is also at the correct Y value to have come from the status screen, but I had since clicked away from the screen.

![dq2_floating_poison_drop](https://user-images.githubusercontent.com/11208054/36185102-086e16f8-10fd-11e8-8a5f-edccfce1eaf6.png)

**Comment by codingthat** [comment] 2018-04-22 14:33
Duplicate of https://github.com/larsiusprime/tdrpg-bugs/issues/1254

**Closed** 2018-04-22 15:17 UTC
