### ISSUE TITLE
Battle Speed Change Crash

### ISSUE THREAD

**Issue by meganbednarz** [larsiusprime/tdrpg-bugs#433] opened 2015-08-05 03:48 UTC
Woohoo! I made the game crash. In the first Coliseum battle, I had just set it to 8x speed but it was a misclick so I clicked fast to set it to 16x speed, and it locked up.

![0 1 9-35_battlecrash_speedchange](https://cloud.githubusercontent.com/assets/597059/9078031/5d680bb2-3afb-11e5-8bf8-43fdf5b1e577.png)

**Comment by larsiusprime** [comment] 2015-08-05 13:20
From the looks of it Azra is taking some damage. There's a known bug where enemies will only spawn from the red zones, and the blue zones seem to just instantly cause Azra damage when they spawn. Wonder if that's the cause...

**Comment by larsiusprime** [comment] 2015-09-07 20:11
This should be fixed now.

**Closed by larsiusprime** 2015-09-07 20:11 UTC
Labels: Battle, bug, DQ CORE
