### ISSUE TITLE
"Invalid UTF-8" crash when entering any battle in Japanese, Korean and Russian

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1011] opened 2016-06-13 00:12 UTC
In short, any language that uses characters not included in UTF-8 encoding will crash. I'm assuming bad crashes like these should get a higher priority.

**Comment by larsiusprime** [comment] 2016-06-13 01:39
Absolutely, flag it "Priority High".

Is it just a pop-up that says "Invalid UTF-8" ? If you run from command
line do you get any stack trace?

On Sun, Jun 12, 2016 at 7:12 PM, ManDude <notifications@github.com> wrote:

> In short, any language that uses characters not included in UTF-8 encoding
> will crash. I'm assuming bad crashes like these should get a higher
> priority.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1011>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-Ioe0fBDJ_tOj8iaYvT6jIqnabe8ks5qLKBrgaJpZM4Iz630>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment] 2016-06-13 03:19
Fixed in 0.9.9 -- caused by trying to use non-UTF8 functions like str.split and str.substr on UTF8 strings

**Closed** 2016-06-13 03:20 UTC
Labels: 1, Battle, bug, DQ CORE, in progress, Localization, Priority HIGH

**Comment by ManDude** [comment] 2016-06-13 03:24
Oops I forgot to provide an image but if it's fixed then awesome.

**Comment by larsiusprime** [comment] 2016-06-14 06:11
Yeah I fixed it, caused by doing unsafe operations on a Utf8 string
(regular string split(), etc, rather than utf8-aware split)

On Sun, Jun 12, 2016 at 10:24 PM, ManDude <notifications@github.com> wrote:

> Oops I forgot to provide an image but if it's fixed then awesome.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1011#issuecomment-225482214>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-B8l1ikd3jmZu6okNE1sPKYmTsVMks5qLM1lgaJpZM4Iz630>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
