### ISSUE TITLE
ranger refuses to attack on Map Old Friends, New Enemies

### ISSUE THREAD

**Issue by farmboy0** [larsiusprime/tdrpg-bugs#705] opened 2016-04-26 20:47 UTC
![dq1](https://cloud.githubusercontent.com/assets/2206262/14833627/92c2b9de-0c00-11e6-97ff-0df19978f7eb.jpeg)
(0.5.3 - demo, build 1) (Linux 64-bit)

**Comment by larsiusprime** [comment] 2016-04-26 22:01
Wow, that's a pretty blatant bug.

For clarity's sake -- did you place Ketta and have the enemies *walk* into range, or were they already there and you *placed* her so that they were suddenly in range from the moment she was summoned?

**Comment by farmboy0** [comment] 2016-04-26 22:13
I placed her first before any enemies arrived.
BTW the same position on the lower part doesnt have this problem.

**Comment by larsiusprime** [comment] 2016-04-26 22:16
Wow well this was easy to reproduce. What the heck is going on?

**Comment by larsiusprime** [comment] 2016-04-26 22:32
This bug is caused by a very strange error -- as we can see from this debug overlay, enemies whose y coordinate in battle tiles is 0 do not appear on the collision map!

![2016-04-26 17_31_19-adobe flash player 17](https://cloud.githubusercontent.com/assets/739064/14836319/d6229dce-0bd4-11e6-960d-0ccd2199a957.png)

Fortunately this is solvable, I'll look into it tomorrow.

**Comment by larsiusprime** [comment] 2016-04-27 14:12
This will be fixed in 0.5.5

The bug was caused because there is a feature where enemies have some random variation to their placement. When they are on square 0,0, this puts some of them at negative positions and outside of the collision area!

Expanding the collision area a bit fixed this.

**Closed** 2016-04-27 14:20 UTC
Labels: 1, bug, DQ CORE, in progress, Priority HIGH

**Comment by farmboy0** [comment] 2016-04-27 16:00
why not just make the randomness not put them at negative positions in the first place? just clamp the pos to 0,0 and maxx,maxy.
What happens when the randomness puts it over max(x,y) position? will this lead to the same error?

**Comment by larsiusprime** [comment] 2016-04-27 17:30
It does do that sort of thing, this was a case of reading from the wrong variable.
