### ISSUE TITLE
Awarded weapons achievements upon buying Evni

### ISSUE THREAD

**Issue by ddueber** [larsiusprime/tdrpg-bugs#1106] opened 2016-06-19 13:51 UTC
I was awarded the achievement for getting all unique weapons AND for upgrading all unique weapons when I bought Evni. It was not my last unique weapon to gain.

**Comment by ManDude** [comment] 2016-06-19 14:16
Dupe of #1081 .

**Closed by ManDude** 2016-06-19 14:16 UTC
