### ISSUE TITLE
"Weapons" button permanently gone after recruiting-until-class-full in first prison

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#708] opened 2016-04-27 08:48 UTC
New game, beat the first battle on normal, then in the prison (had 300% scrap :) ) hired new bezerkers untill class was full.  After that, only the "recruit" button remains at the bottom, left-aligned where the "weapons" button initially was.  0.5.3 full, win7x64.

**Comment by IBwWG** [comment] 2016-04-27 08:50
Actually, it's permanent.  After leaving and reentering, still the same.
[export-prison-no-weapons.zip](https://github.com/larsiusprime/tdrpg-bugs/files/238272/export-prison-no-weapons.zip)

**Comment by IBwWG** [comment] 2016-04-28 13:05
OK, not quite permanently.  Redoing the previous battle on Advanced (and failing) made Weapons reappear in the prison.

**Comment by larsiusprime** [comment] 2016-04-28 18:58
I think what's happening here is it's got some side effect of a recent change with upgrade stores -- if you can't afford anything, it hides the button. You can test my directly hacking your save file's gold variable, but I think it's clear this is the cause.

**Comment by IBwWG** [comment] 2016-04-28 19:13
Oh, I see...but what if I want to see what I can't afford, so I can save up?  Or sell what I have?  :)  Also, when this applies to Weapons but not Recruit, I find it a bit confusing.  But you're absolutely right, that save has 18 gold only, so I probably couldn't afford weapons, but I didn't know that at the time.

**Comment by larsiusprime** [comment] 2016-04-28 20:17
Yeah I mean it's a bug. It's supposed to show you the weapons button :)

**Comment by IBwWG** [comment] 2016-04-28 20:19
Oh, gotcha.  :)  Oops.

**Comment by larsiusprime** [comment] 2016-05-02 15:49
Fixed in 0.5.9

**Closed by larsiusprime** 2016-05-02 15:49 UTC
Labels: 1, bug, DQ CORE, Priority HIGH
