### ISSUE TITLE
Null object reference error

### ISSUE THREAD

**Issue by JOJ650s** [larsiusprime/tdrpg-bugs#1170] opened 2016-07-03 01:13 UTC
Hello, I been playing and enjoying the new update recently, but I have ran into quite the error.
On any level it seems, as soon as one of my defenders goes to attack, I get the pop-up error "Null object reference."

My PC is running Windows 7 64bit.
The game version is 3.0.6a, and no mods are being used.
Here's the error.txt
[_error.txt](https://github.com/larsiusprime/tdrpg-bugs/files/344816/_error.txt)

**Comment by larsiusprime** [comment] 2016-07-03 01:17
Interesting!

What language are you using, incidentally? English or something else?

The error.txt suggests the issue is with a battle number or other textual
notification; while I'm fixing this you might workaround it by going to
options->miscellaneous and turning off battle numbers. Does that fix it? If
it does then that confirms my suspicions and I know exactly where to go to
try to patch this.

On Sat, Jul 2, 2016 at 8:13 PM, JOJ650s <notifications@github.com> wrote:

> Hello, I been playing and enjoying the new update recently, but I have ran
> into quite the error.
> On any level it seems, as soon as one of my defenders goes to attack, I
> get the pop-up error "Null object reference."
>
> My PC is running Windows 7 64bit.
> The game version is 3.0.6a, and no mods are being used.
> Here's the error.txt
> _error.txt
> <https://github.com/larsiusprime/tdrpg-bugs/files/344816/_error.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1170>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-KvVCAFKcMYTRnQVMm8QcRE0EQHBks5qRwyxgaJpZM4JDx-v>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by JOJ650s** [comment] 2016-07-03 01:46
Yup, I am indeed using English.
I tried the hide battle numbers option, and everything seems to be working, which is great!

**Comment by larsiusprime** [comment] 2016-07-04 15:39
I put in a null guard in 2.0.6b which I'm pushing to steam now. I applied another fix too, and after that I wasn't able to reproduce this locally.

Can you test 2.0.6b when it goes up and let me know if that works for you?

**Comment by JOJ650s** [comment] 2016-07-04 15:54
I went ahead and did a level with the numbers on, and everything worked perfectly!

**Comment by ManDude** [comment] 2016-07-04 19:09
Awesome! Closing this now. Reopen if it happens again.

**Closed by ManDude** 2016-07-04 19:09 UTC
Labels: 1, bug, DQ CORE, Please Verify
