### ISSUE TITLE
Splash on Ice Splash is 0 no matter what level it is

### ISSUE THREAD

**Issue by jungsosh** [larsiusprime/tdrpg-bugs#1051] opened 2016-06-15 17:02 UTC
The info on ice splash says it does 0 splash damage for 0 tiles no matter what level it is. Unsure if this is just a display bug, or actual gameplay bug.

This is on Windows 7 64-bit Steam DQ1 2.0

If it matters, the save is imported from the legacy version.

**Comment by ManDude** [comment] 2016-06-15 17:08
Just a display bug.

**Comment by CoqPwner** [comment] 2016-06-16 01:05
Yup, having this same issue with Windows 8 64 bit here. I'm fairly sure the skills work as intended, only the visuals appear wrong.
For example, when you level up the skills you can see in the green the actual full value of the damage, instead of just the boost it should give.

**Comment by larsiusprime** [comment] 2016-07-11 21:59
Fixed in 2.0.8

**Closed** 2016-07-11 22:00 UTC
Labels: 1, Battle, bug, DQ CORE, Priority MID
