### ISSUE TITLE
Yougot window will show "EQUIP" button if the item is a skull and another popup is queued.

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#860] opened 2016-06-04 15:18 UTC
Easy to reproduce in a new NG+ game by going to the 3rd level, selecting extreme and winning. Since you get 1 Stone Skull + 3 Stone Skulls, 2 Yougots appear and the first one has the EQUIP button while the second one does not.

**Comment by ManDude** [comment] 2016-06-04 15:29
![dq12](https://cloud.githubusercontent.com/assets/7569514/15800441/82933b9e-2a71-11e6-95c1-2e6d82d7c2e8.png)

**Comment by IBwWG** [comment] 2016-06-04 16:39
I think this is a dupe of https://github.com/larsiusprime/tdrpg-bugs/issues/802 but it's nice to have a screenshot for clarity :)

**Closed** 2016-06-08 16:22 UTC
Labels: duplicate
