### ISSUE TITLE
New Game + Journal issues

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#737] opened 2016-05-01 19:37 UTC
0.5.7, I got to read IIRC the first 7 "Secrets" entries, left the game, game back, finished a battle, then saw this.

- [ ] For whatever reason the Day 3: Addendum is highlighted (also when you click on it, the rest of the text is grey except the Addendum), even though I remember reading it the first time through the game.  (Maybe it wasn't supposed to show until New Game+ ? )
- [ ] The Secrets tab is gone
- [ ] Clicking the highlighted Day 3: A does not make the (1) go away from the journal afterwards

![dq-newgp-journal-huh](https://cloud.githubusercontent.com/assets/16719964/14943872/e5dc8cd4-0fe4-11e6-9638-91b0e5d02209.png)

**Comment by IBwWG** [comment] 2016-05-01 19:40
After the prison, these problem persist:

![dq-newgp-journal-huh2](https://cloud.githubusercontent.com/assets/16719964/14943891/483d6678-0fe5-11e6-8e03-e8eec01cafcb.png)

(Now it permanently says (2) beside the journal.)

**Comment by larsiusprime** [comment] 2016-05-02 15:59
Okay, so this is a mix of potentially legitimate bugs and mostly just a result of a mismatch of design intention vs. user understanding (which still counts as a "bug").

You see, in New Game+, it's a retelling of the original story *with more details*. IE, there's new content in the journal you won't see in the original playthrough. If we just treated the new content the same as the old content, we were afraid the user would not notice the new stuff and just feel like ignoring the journal.

So in the new system, what we do is that we show all the entries you've unlocked in regular mode, and then make them half-transparent to indicate they're unlocked, but not unique to NG+. Then, New Game+ can unlock two kinds of entries:

- [ ] Entirely new entries
- [ ] Tack on additional lines/pages to existing entries

These will be marked as "new" in the journal entries. So it's possible that everything's working as intended, you just haven't visited the new material yet.

All that said, clearly this didn't line up with what you were expecting. Got any ideas for how we can communicate, "hey you unlocked this NEW journal entry you haven't seen before?" but still make it so you can read the rest of the journal material you've unlocked from the original game?

**Comment by IBwWG** [comment] 2016-05-02 16:06
I think I understand the intention, mostly.  When you say "additional lines" do you mean entire Addendum entries, or do you mean Addendum entries are part of the original and then they are modified in NG+?  Because: my original playthrough had these Addendum entries.

**Comment by larsiusprime** [comment] 2016-05-02 16:08
I mean that there's additional lines to any sort of main entry (including both day entries and addendums). This is because there are certain events in NG+ that have their own entries, and minor commentary in regular entries that refer to them, that would be anachronistic without the main entries.

Like, say, an entry for a dream Azra has that she mentions in passing in another entry. In regular game, we cut the passing line, in NG+ we paste it back in.

**Comment by IBwWG** [comment] 2016-05-02 16:31
OK, but the Day 3 Addendum had literally *nothing* I hadn't read the first time, it seemed.  I'll check the others, but it had seemed the same.  Meanwhile, the journal indicator has at some point gone away, so I guess that wasn't so permanent after all.  Nonetheless, it did happen on the first few battles through NG+.  I have my save from just before NG+ exported, so I think I could try to see if it's repeatable.

Plus that wasn't the only issue, I mean I made a list of three.  :)

**Comment by IBwWG** [comment] 2016-05-02 16:32
And actually the second issue, that there is no Secrets tab anymore, persists, even though I had already gotten to read some.

**Comment by larsiusprime** [comment] 2016-05-02 16:32
Yeah, I'm looking into the other two. The missing secrets tab is definitely a bug.

**Comment by IBwWG** [comment] 2016-05-02 16:34
OK.

Just checked Night 3 Addendum and it was also the same as the original playthrough.  I'm even more sure of that one, since it's so short.

**Comment by larsiusprime** [comment] 2016-05-02 16:35
Cool, thanks for that. So another bug -- either the indicator is misreading things, or the addendum is not showing the extra text that it should.

**Comment by larsiusprime** [comment] 2016-05-09 21:47
Final to do list:
- [ ] Ensure normal game entries show up in NG+
- [ ] Normal game entries not unlocked in NG+ but unlocked in normal game should be visible but faded out
- [ ] Normal game entries unlocked in both NG+ and normal game should be visible and solid

**Comment by IBwWG** [comment] 2016-05-31 10:21
![dq-journal-1-no-highlight](https://cloud.githubusercontent.com/assets/16719964/15671198/e2528bac-2729-11e6-9f35-9a6edde4b47b.png)

0.7.8, win7x64, HD mode@1704x960windowed

AFAICT here, still an issue (two of the three original ones): NG+, but the Secrets tab is gone; journal icon on map shows "1", but journal has no new highlighted entries.

Save file: [export-journal.zip](https://github.com/larsiusprime/tdrpg-bugs/files/290840/export-journal.zip)

**Comment by IBwWG** [comment] 2016-05-31 11:25
After beating a level, secret tab is still missing, and icon shows 2 but journal only shows 1 highlighted entry.  I'm guessing that maybe the second one is on the hidden secret tab.  So maybe fixing that fixes everything.

![dq-journal-2-no-highlight](https://cloud.githubusercontent.com/assets/16719964/15672790/0fe9b514-2733-11e6-9d7d-3bbc22a6dae2.png)

**Comment by IBwWG** [comment] 2016-05-31 11:27
Also is the "next page" thing missing, or just an end quote here?  :

![dq-journal-next-missing-maybe](https://cloud.githubusercontent.com/assets/16719964/15672847/64316c34-2733-11e6-855a-f5686e97bcbf.png)

**Comment by IBwWG** [comment] 2016-05-31 13:49
This continues as I beat levels in NG+, the counter is now "2" (was 3, then I read the 1 available passage) but with only the Index tab showing.  I bet the 2 are stuck in secrets.

**Comment by larsiusprime** [comment] 2016-05-31 14:22
Thanks!

- [ ] Fix secrets tab in NG+
- [ ] Fix missing "next" button (there should be one on bookkeeping).

**Comment by larsiusprime** [comment] 2016-05-31 18:11
Okay so I added a fix to the save import script in 0.8.0 and it fixes the weirdness that was wrong with your save (it doesn't occur in new NewGame+ runs, maybe the result of using a development build).

Working on the missing "Next" button.

**Comment by larsiusprime** [comment] 2016-05-31 18:22
Okay fixed the missing "next" button -- I had typed "bookk*e*ping" somewhere instead of "bookk*ee*ping"

**Comment by larsiusprime** [comment] 2016-05-31 18:23
Fixed in 0.8.0

**Closed by larsiusprime** 2016-05-31 18:23 UTC
Labels: 5, bug, DQ CORE, Priority HIGH
