### ISSUE TITLE
Meteor Strike occurs randomly when zapping Blue Crystals, can kill weak party members.

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1263] opened 2016-11-27 16:53 UTC
I've noticed a few times now that long after enemies have moved out of range of my warriors I'll detonate a blue crystal vein next to the enemies and some of my warriors would die even though they are on the opposite side of the screen (like 20 or so squares away).

When this happens some of the Healers get stuck repeatedly healing nothing.

I've tried recording it but I can't seem to intentionally reproduce it :/

Windows 10 x64
Steam
Latest stable recommended version

**Comment by Nicholas-Steel** [comment] 2016-11-28 17:20
I believe I can't reproduce it because I've leveled my characters up since noticing it.

**Comment by larsiusprime** [comment] 2016-11-28 17:33
Thanks for this, let me know if it happens again and see if you can find any more details that might be causing it. Does it happen often or rarely?

**Comment by Nicholas-Steel** [comment] 2016-11-29 06:16
I've got a recording, just gonna edit it down in size and upload it to youtube so 30~ minutes maybe.

**Comment by Nicholas-Steel** [comment] 2016-11-29 06:27
It looks like an unexplained mechanic involving the blue crystals that you hit with lightning, causes a fireball to fall from the ceiling and strike a random party member, if the party member dies from this any healers in the vicinity will get stuck spamming heal.

**Comment by Nicholas-Steel** [comment] 2016-11-29 06:28
The fireball striking a random party member when you strike one of the pre-placed blue crystals is the unexplained mechanic.

**Comment by Nicholas-Steel** [comment] 2016-11-29 06:33
It's gonna take a while to upload (Maybe 20 minutes) but the video will be available here when it finishes: https://youtu.be/KdMlcd_0sqE

Watch the 2 vertically aligned healers in the top left. One will die when I strike a blue crystal and the other will get stuck spamming heal even when nothing in its vicinity is hurt.

**Comment by Nicholas-Steel** [comment] 2016-11-29 06:48
Video is available.

**Comment by ManDude** [comment] 2016-11-29 09:55
Ahhh. I knew about the fireball bug (#984) but I always thought it didn't do anything (since it doesn't hit enemies afaik).

**Comment by larsiusprime** [comment] 2016-11-29 16:39
Ah, good to have a solid reproduction case for this. The stray fireball is *definitely* a bug.

**Comment by larsiusprime** [comment] 2016-12-20 22:16
Reproduced, working on it.

**Comment by larsiusprime** [comment] 2016-12-20 22:28
Fixed in 2.1.2

**Closed** 2016-12-20 22:29 UTC
Labels: 1, Battle, bug, DQ CORE, Priority HIGH
