### ISSUE TITLE
"Bonus" menu dims the background incorrectly at 1920x1080

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1279] opened 2016-12-11 07:03 UTC
Click the yellow Bonus button while on the map then click a Mission, the background doesn't properly dim (dims only a portion of it). The amount of screen that is dimmed is further reduced if you access the Bonus menu in NG+.

1) Access the Bonus menu via the yellow button on the Map (NG and NG+ affected).
2) Click a Mission to view its description.
3) Note how the background is dimmed improperly.

Windows 10 Pro AU x64

**Comment by larsiusprime** [comment] 2016-12-20 19:56
Fixed in 2.1.2

I believe this actually was caused by the background dimming not respecting the map scroll, and appearing off-screen.

**Closed** 2016-12-20 19:57 UTC
Labels: 1, bug, DQ CORE, Overworld, Priority HIGH

**Comment by Nicholas-Steel** [comment] 2017-02-27 19:17
Seems to be fixed in v2.1.5.
