### ISSUE TITLE
Bug after "The Way Out" ending, oversight in Journal

### ISSUE THREAD

**Issue by Hinarv** [larsiusprime/tdrpg-bugs#1177] opened 2016-07-04 19:24 UTC
Version 2.0.6 b

After completing "The Way Out" and starting again with the same character, a cutscene window pops up, completely black. Clicking Next or Previous gives a Null Object error, so you must skip it.

![bork1](https://cloud.githubusercontent.com/assets/5992820/16568689/24dd6a58-4225-11e6-9319-895f27de89d4.PNG)

Also, another thing: in "Day 26 - Evni", on the second page it says "Slak, seated nearby and believing herself unobserved", when it should say Ketta.

![slak](https://cloud.githubusercontent.com/assets/5992820/16568695/2ec1fb10-4225-11e6-9887-ec36eeb16ab8.PNG)

**Comment by larsiusprime** [comment] 2016-07-05 21:51
What version of the game were you using? And what operating system? (looks like windows?)

Title screen shows the version on the lower right hand corner.

**Comment by larsiusprime** [comment] 2016-07-05 21:54
Fixed the journal bug.

As for the cutscene issue, can you clarify a bit?

> After completing "The Way Out" and starting again with the same character, a cutscene window pops up, completely black. Clicking Next or Previous gives a Null Object error, so you must skip it.

So to be clear:
- Complete the normal game by beating "The Way Out"
- "Start again with the same character" -- Reload that save slot?

**Comment by larsiusprime** [comment] 2016-07-05 21:57
Okay reproduced!

**Comment by larsiusprime** [comment] 2016-07-05 22:05
Fixed in 2.0.7b

**Closed** 2016-07-05 22:05 UTC
Labels: 1, bug, Cutscene, DQ CORE, DQ1
