### ISSUE TITLE
Crash: Null Object Reference [2.0.4 c]

### ISSUE THREAD

**Issue by kindasmitten** [larsiusprime/tdrpg-bugs#1140] opened 2016-06-24 04:57 UTC
When I try to start a battle, the game area goes black and a popup says "Null Object Reference." I tried several different battles, story ones and bonus ones, they all cause this error. I tried the new opengl version and it behaves the exact same, null object reference crash when starting a battle. Hope I did this bug report right:

Operating System: Windows 10 Pro
Browser/Download: Download 
Demo/Full?      : Full Version
Version #       : Steam DQ1 2.0.4 c
Graphics card: GTX 650 Ti Boost
CPU: i5-3350P @ 3.10ghz
Ram: 8GB
Native resolution: 1920x1080 60hz
Game resolution: windowed, 1280x960 (4:3)
Screenshot: http://puu.sh/pDYDh/3cd9c64ca1.png

Steps to reproduce:

1. start any battle, doesn't matter which
2. receive popup error and game crash

What I expect to happen:

click begin to start the battle, then the battle starts

What happens instead:

click begin and game crashes, popup says Null Object Reference

**Comment by larsiusprime** [comment] 2016-06-24 14:36
Hm, this is really weird! 

I can't reproduce this myself, can you export your save file and attach it here?

**Comment by IBwWG** [comment] 2016-06-25 16:51
Have you tried with the original non-HD graphics in the video settings?

**Comment by larsiusprime** [comment] 2016-06-29 21:23
Have you seen this happen in 2.0.5c?

**Comment by larsiusprime** [comment] 2016-07-19 14:57
Closing for now, I believe this is fixed.

**Closed by larsiusprime** 2016-07-19 14:57 UTC
Labels: 1, Battle, bug, DQ CORE, Please Verify
