### ISSUE TITLE
Scaling issue only in alt-tab thumbnail

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1253] opened 2016-11-10 22:15 UTC
win10, 2.0.8b, 1920x1080 fullscreen hd.

![dqscale](https://cloud.githubusercontent.com/assets/16719964/20196592/5b45a2b4-a769-11e6-9fb2-9bf084a45ebe.png)

Sounded related to #1251 but not the same impact obviously.

**Comment by larsiusprime** [comment] 2018-01-19 16:16
Closing for now, as it's low priority by itself, and it's probably actually caused by the other bug anyway.

**Closed by larsiusprime** 2018-01-19 16:16 UTC
Labels: 1, DQ CORE, Priority LOW, bug, windows
