### ISSUE TITLE
Archshepherd Stave+'s and Beast's Weapon+'s 3x DMG trait is broken

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#926] opened 2016-06-07 04:16 UTC
![dq04-1](https://cloud.githubusercontent.com/assets/7569514/15845769/2657319c-2c6e-11e6-9588-c85571a4ee9b.png)
![dq04](https://cloud.githubusercontent.com/assets/7569514/15845768/262d7b72-2c6e-11e6-8dbb-d540de7d91d5.png)
??? Am I missing something here?

**Comment by larsiusprime** [comment] 2016-06-07 17:30
Does their equipment give them criticals?

**Comment by ManDude** [comment] 2016-06-07 18:26
That's why I posted the full game image while selecting them. No, it doesn't.

- Healer: Archshepherd Stave+ gives 3x DMG vs. Sheep; Silk Gambeson+ gives 45 DEF.
- Ice Mage: The Beast's Weapon+ gives 3x DMG vs. Worm and Splitter; Horseman's Lamellar+ gives 30% MAGIC DMG resist.

**Comment by larsiusprime** [comment] 2016-06-07 19:03
No, the only thing that affects critical hits is skills & equipment, it's not tied to any stats at all. I'll look into this.

**Comment by Jym77** [comment] 2016-06-16 07:40
I got the same impression after equipping the Beast Weapon+.
I assumed the 3x DMG was applied to every enemy and not just worms.

**Comment by GameKnut** [comment] 2016-06-22 18:17
As of 6/22 (2.0.3a), the Beast's Weapon+ appears to still be broken.
I gave it to Wrenna (level 33, attack 68+47; armor is Purity of Flame (+50), but that doesn't matter, I think). Her Ice Splash is level 5; at Boost 5, its expected damage (according to the tooltip) is about 770.
In actuality, her Ice Splash is hitting for about 7.3k damage on everything (haven't tested cultists, to be honest) nearly ten times as much.
I'm no programmer, but I think that means it's not -just- applying the x3 damage against worms/splitters to everything else; something else is going wrong, as well.

**Comment by ManDude** [comment] 2016-06-22 18:40
I think it's the 3x DMG that's breaking everything. I need to test this more.

**Comment by PaladinOne** [comment] 2016-06-25 01:08
It's probably that the 3x Damage effect isn't correctly checking for the specific type of enemy it's supposed to target, and is just applying 3x to everything.

**Comment by larsiusprime** [comment] 2016-06-25 04:29
That assessment seems correct; it should only apply to enemies with the "worm" and "apc" type, but the check is probably not working.

**Comment by ClaudioBasckeira** [comment] 2016-06-29 23:58
I can confirm it happening on 2.0.4c and can also confirm the damage is about 10x normal, not 3x.

**Comment by larsiusprime** [comment] 2016-06-30 00:43
I'm fixing this in the next build, 2.0.6

On Wed, Jun 29, 2016 at 6:58 PM, ClaudioBasckeira <notifications@github.com>
wrote:

> I can confirm it happening on 2.0.4c and can also confirm the damage is
> about 10x normal, not 3x.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/926#issuecomment-229524037>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-MHa-2KefFj6OxyQzUnyjWYWxilGks5qQwalgaJpZM4IviqV>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment] 2016-06-30 00:50
Can confirm that it's dealing 3x Crit DMG to every enemy.

LVL60 + Holy Light LV9 + Boost 5 + Archshepherd Stave+ = 334 DMG. 334 * 3 = 1002 DMG (shown in 1st screenshot).

**Comment by ManDude** [comment] 2016-06-30 00:51
![dq05](https://cloud.githubusercontent.com/assets/7569514/16473458/32967e6e-3e65-11e6-871f-63f5549ba4e4.png)

**Comment by larsiusprime** [comment] 2016-06-30 00:52
Yeah what happens is it skips the vs_type check, and since there's two of
those (splitters and worms) it can potentially apply the critical effect
twice

On Wed, Jun 29, 2016 at 7:50 PM, ManDude <notifications@github.com> wrote:

> Can confirm that it's dealing 3x Crit DMG to every enemy.
>
> LVL60 + Holy Light LV9 + Boost 5 + Archshepherd Stave+ = 334 DMG. 334 * 3
> = 1002 DMG (shown in 1st screenshot).
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/926#issuecomment-229531286>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-DvGone0yulxx0ssoWsemScrFsjJks5qQxLvgaJpZM4IviqV>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment] 2016-06-30 01:00
Wrenna is doing 9x DMG, just checked.

LVL 60 + Ice Splash LV9 + Boost 5 + Beast's Weapon+ = 1521 DMG. 1521 * 9 = 13689 DMG (see 2nd screenshot).

**Comment by ManDude** [comment] 2016-06-30 01:01
Changing priority cause huge balancing issue.

**Comment by larsiusprime** [comment] 2016-06-30 01:50
Yeah this needs to go first on my list for the next patch.

On Wed, Jun 29, 2016 at 8:01 PM, ManDude <notifications@github.com> wrote:

> Changing priority cause huge balancing issue.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/926#issuecomment-229532594>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-JbS8NyAB_qrG8Y8WmlUOWL903S5ks5qQxVWgaJpZM4IviqV>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment] 2016-07-11 02:56
This is fixed now for sure.

**Closed by larsiusprime** 2016-07-11 02:56 UTC
Labels: 1, Battle, bug, DQ CORE, Priority HIGH
