### ISSUE TITLE
DQ1 "reward" and "bonus for the ideal" not translated into russian.

### ISSUE THREAD

**Issue by domitri** [larsiusprime/tdrpg-bugs#1308] opened 2017-03-01 10:19 UTC
DQ1 "reward" and "bonus for the ideal" not translated into russian.

Version 2.1.5
Windows 10 x64
1680x1050 (Fullscreen)
russian localization game
![untitled-3](https://cloud.githubusercontent.com/assets/24471323/23455774/7f681de0-fe79-11e6-9f20-1cadc9ee147e.jpg)

**Comment by larsiusprime** [comment] 2017-03-01 14:16
Thanks very much, I'll get right on this and try to get a hotfix out.

**Comment by larsiusprime** [comment] 2017-03-01 23:42
I've found the cause. There was a bug in my localization script, it affected several languages, including Russian. It will be fixed in 2.1.6

**Closed by larsiusprime** 2017-03-01 23:42 UTC

**Comment by domitri** [comment] 2017-03-02 07:41
Thank you very much for efficiency.
Please note Baсklog 1307 and 1306.

Have a nice day.
