### ISSUE TITLE
Tileset glitch at desktop resolution

### ISSUE THREAD

**Issue by LarsMadeMeDoIt** [larsiusprime/tdrpg-bugs#1224] opened 2016-08-27 18:55 UTC
A while ago, when I was checking out #1214  I noticed that at maximum resolution I got these vertical lines on the central and SE area of the map (more or less the same titles that hide the passages to the underground city and ET's prison).

 After a bit more testing today, it appears that this happens only in windowed mode when the resolution is set to match the desktop's. Lower resolutions are fine. Also, switching to fullscreen mode and then back to windowed temporarily fixes it, until the next game restart.

![stripes](https://cloud.githubusercontent.com/assets/20359621/18029382/09d93754-6c97-11e6-901d-892de2f920de.jpg)
![stripes1](https://cloud.githubusercontent.com/assets/20359621/18029384/0f9304f4-6c97-11e6-870a-44edc0553e67.jpg)

 I'm using Vista with a Geforce GT 430. Drivers are up to date as far as I can tell.

**Comment by IBwWG** [comment] 2016-11-03 14:15
Dupe of #1067

**Closed by IBwWG** 2016-11-03 14:15 UTC
Labels: 1, bug, DQ CORE
