### ISSUE TITLE
dragon graphic missing (classic graphics)

### ISSUE THREAD

**Issue by pszxzsd** [larsiusprime/tdrpg-bugs#1171] opened 2016-07-03 10:26 UTC
Operating System: Linux 32bit (Ubuntu 16.04)
Browser/Download: Download, Steam
Demo/Full?      : Full Version
Version #       : 2.0.5c
Optional Info** : Netbook, 1024x600 screen, fullscreen, graphics set to classic (not HD)

In the levels the dragon is just a big black square, looks like the old school tile for it is simply missing.

**Comment by larsiusprime** [comment] 2016-07-04 16:21
I can't reproduce this on that resolution, though to be fair I'm not running a 32-bit linux netbook. How old is the netbook? What are its specs? I don't *feel* like you should be getting a silent out-of-memory error with those graphics settings, but it's a possibility.

As far as I can tell the dragon's old sprite graphic is in place and no one else has reported this, so I'm assuming it's a system error of some sort, such as a memory error.

Is it only the dragon? Does the behavior change if you summon characters in a different order (were you summoning the dragon first or last?)

**Comment by pszxzsd** [comment] 2016-07-05 15:19
The netbook is from the late middle ages and has an Atom N270 CPU, integrated GMA 950 "graphics" and 1 GiB RAM.

It's indeed only the dragon and the placing order makes no difference. I also tried running the game windowed 800x600 and it makes no difference either. Steam says the game cache is all fine, so it's not data corruption.

Then I tried switching to the HD graphics set and to my surprise this actually works, with dragon and all! This seems to indicate that it's not a memory or driver issue.

Alas, the HD graphics work only in 800x600 mode for me. When I switch back to fullscreen 1024x600 mode I get crashes with "SIGFPE (Floating point exception)". This seems related to #568.

**Comment by larsiusprime** [comment] 2016-07-05 15:30
I wonder if it has to do with png encoding or something. You could try
going into the game's asset files, finding the original-art version of the
graphics, and opening & resaving them in gimp or something?

On Tue, Jul 5, 2016 at 10:19 AM, pszxzsd <notifications@github.com> wrote:

> The netbook is from the late middle ages and has an Atom N270 CPU,
> integrated GMA 950 "graphics" and 1 GiB RAM.
>
> It's indeed only the dragon and the placing order makes no difference. I
> also tried running the game windowed 800x600 and it makes no difference
> either. Steam says the game cache is all fine, so it's not data corruption.
>
> Then I tried switching to the HD graphics set and to my surprise this
> actually works, with dragon and all! This seems to indicate that it's not a
> memory or driver issue.
>
> Alas, the HD graphics work only in 800x600 mode for me. When I switch back
> to fullscreen 1024x600 mode I get crashes with "SIGFPE (Floating point
> exception)". This seems related to #568
> <https://github.com/larsiusprime/tdrpg-bugs/issues/568>.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1171#issuecomment-230509966>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-JFexvnWU3GhL2xNOjDC48qMd2hlks5qSnX_gaJpZM4JD19F>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by pszxzsd** [comment] 2016-07-08 11:36
I resaved the tiles in question with gimp and ran them through optipng, neither fixed the problem. I also looked at the meta data, but if those graphic files are any different from the others I don't see the difference. Maybe it's an unfathomable corner case with my setup. Anyway, the HD graphics work fine, consider me a happy customer, except for that floating point crash in fullscreen mode.

**Comment by larsiusprime** [comment] 2016-07-19 14:56
Thanks for bringing this up, I haven't had any other reports yet, so I'll just close this for now, but if we see it again then we'll know it's not just you and we'll try to dig into it.

**Closed by larsiusprime** 2016-07-19 14:56 UTC
Labels: 1, Battle, bug, DQ CORE
