### ISSUE TITLE
Sidequest 4 doesn't unlock after beating sidequest 3

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#869] opened 2016-06-04 17:34 UTC
![dq19](https://cloud.githubusercontent.com/assets/7569514/15801100/d87ec260-2a82-11e6-9c0a-47c6218761ed.png)

**Comment by larsiusprime** [comment] 2016-06-04 18:32
Can you send me your save file for this one?

**Comment by ManDude** [comment] 2016-06-04 19:14
[SAVE_SLOT_2.zip](https://github.com/larsiusprime/tdrpg-bugs/files/298985/SAVE_SLOT_2.zip)

**Comment by IBwWG** [comment] 2016-06-04 21:12
Also happened to me.  Never knew there was a sidequest 4... :)

**Comment by larsiusprime** [comment] 2016-06-08 02:25
Okay, so this bug is caused by a simple oversight -- only battles, not sidequests, are treated as "started" when you start them, and the progression script needs to check "started" for the triggers.

I've put in two fixes -- now starting a sidequest will really mark it as "started", and I put a save file cleanup script that checks to see if you have beaten any of the sidequests, and if so, retroactively counts them as "started."

This means that when you load an old save with this glitch, it will instantly correct it, and then hopping onto the overworld will show you like 7 cutscenes you missed and unlock the next sidequests and such.

Fortunately since we caught this in beta testing you guys will be the only real ones to see this bug.

**Comment by larsiusprime** [comment] 2016-06-08 02:27
Fixed in 0.9.0

**Closed** 2016-06-08 02:27 UTC
Labels: 1, bug, DQ CORE, Overworld, Priority HIGH
