### ISSUE TITLE
Text/Graphical Shearing

### ISSUE THREAD

**Issue by Rythe** [larsiusprime/tdrpg-bugs#271] opened 2015-03-28 07:21 UTC
Text & Graphical Shearing at 854x488

**Comment by Rythe** [comment] 2015-03-28 07:28
DQ1 0.1.1 Build 4, Windows version.

There's text and graphical shearing at 854x488, the min 16:9 resolution.  It looks like it can't consistently decide how to scale the assets at this resolution, so it's like sometimes it'll decide text is 12px tall, then 11px, then 10px. I noticed it a little bit of this during loading screens at higher widescreen resolutions, but worked itself out at game menu proper.  I put an arrow in where this effects the menu buttons.

![0 1 1-gfxshearing](https://cloud.githubusercontent.com/assets/11690153/6880168/072c0b28-d4f2-11e4-92d0-98415b6e94a2.png)

**Comment by ManDude** [comment] 2015-03-28 14:08
See issue #269 :)

**Comment by Rythe** [comment] 2015-03-30 18:24
Issue #269 is the text isn't position correctly.

Issue #271 is that text and things aren't being rendered correctly. That's different, and wasn't present in your screenshot, so has a pretty good chance of being a different issue, so I submitted it at as such.

Oh, and this is on Windows 7.

**Comment by Rythe** [comment] 2015-03-30 19:32
And managed to reproduce at 1288x968. A 4:3 option.

![0 1 1shearing](https://cloud.githubusercontent.com/assets/11690153/6904667/24fb02e2-d6e8-11e4-939a-d5755ff2904c.png)

And then full screen. I'm beginning to think your engine just doesn't do scaling well.

But I suppose I'll toss in my video card specs just because:  Radeon R9 200 series, 14.12 AMD Catalyst Drivers

**Comment by larsiusprime** [comment] 2015-03-30 19:35
Trying to reproduce now.

**Comment by larsiusprime** [comment] 2015-03-30 19:43
850x480*

Here's what I'm getting with the latest build:
![850x480](https://cloud.githubusercontent.com/assets/739064/6905073/1acba3c8-d6eb-11e4-8487-ab620696f014.png)

Zooming in I don't have the artifacts that you do. Granted, I made a slight change to the rendering backend in this build.


*(it's 480, not 488, but the font does the 0-slash thing so it might look like an 8)

**Comment by larsiusprime** [comment] 2015-03-30 20:23
I'm moving this bug into "please verify" for now, in that I think this will be fixed in the next build (DQ1 version 0.1.2), and if I can get confirmation of that I'll close it while I continue to look into things.

I'm not sure what caused the shearing for you, it seems like something I've seen before when the window is accidentally manually resized by a single pixel or two...

**Comment by Rythe** [comment] 2015-03-30 20:36
Ah yes, I see the difference now.  The horizontal 0-slash makes me quick read it as an '8', especially with the inconsistent rendering.

I'm really not sure what's causing the inconsistent scaling here. Everything is about 97% right at 1400x1050, as opposed to the 90% right with most other resolutions. I don't think it's a hardware glitch because it's too consistent per resolution setting over multiple resolution changes on my end, and my other 2D games like Factorio and Tales of Maj'Eyal work fine.

**Comment by larsiusprime** [comment] 2015-03-30 20:39
It might be an artifact of the rendering backend. I just switched from OpenFL's "legacy" mode to "next" mode (blah blah technical bits) so it might be that change. I'm compiling a new build now, when it pops on the server give it a whirl and see if the artifacts are still there for you?

**Comment by larsiusprime** [comment] 2015-03-30 20:51
It's up now.

**Comment by Rythe** [comment] 2015-03-31 00:53
Win 7
DefQ1 (0.1.2 Build 7), Windowed

The new rendering backend fixed most of it, but some problems persist.

Now it mostly looks like bugs in the shadow/emboss/whatever filters going on with the font and buttons n' things. Like it doesn't finish updating the pixels like it should, or screws up which row of pixels its working on.

![moregfx](https://cloud.githubusercontent.com/assets/11690153/6910238/4c6de776-d716-11e4-95c0-3d3bc94fe07b.png)

**Comment by larsiusprime** [comment] 2015-03-31 18:25
That's really strange, because there isn't actually any filtering or post-processing going on, it's static assets. Granted, they're 9-slice-scaled, perhaps that has something to do with it. The smudging on the radio buttons and text is weird too... does this happen with all resolutions or just certain ones?

Also a few sanity checking items:
- [ ] Are you able to manually resize the game window? (You should not be able to)
- [ ] If you take a screenshot, and look at the game canvas, is it different from what it should be? (IE, 1024x768 is actually 1023x769 pixels or something)

I'll keep investigating this and see if I can reproduce. I did see this smudging behavior on my own local builds once, but only when running on a mac, and your report says Windows 7, same thing I've got.

Do you have some details on your graphics card, incidentally?

**Comment by Rythe** [comment] 2015-03-31 19:44
All resolutions. Some resolutions are just cleaner about it than others.

I am not able to manually resize a window.

I sliced down a screenshot to just the rendering area (no window frame), and it was the appropriate 1600x900, which is the resolution the last set of screenshots came from I think. 

As an experiment with the resizing, I tried fullscreen 1920x1080, and everything was good except the game select/options windows, the naming Azra interface, and the Psi/HP numbers and text in battle.

...I might have just figured it out. Or at least part of it. When you click options, a clean and correct scroll window pops up for the various options. But when you then select 'Video' options, a white frame is drawn around the borders of the rendering area, and said video options are all sorts of messed up.  It's probably the video options screen getting shrunk 4 pixels each dimension without any proper scaling going on.

![whiteframe](https://cloud.githubusercontent.com/assets/11690153/6927637/45800ea0-d7b4-11e4-9781-3a98be3aa02d.png)

But to restate my vid card - Radeon R9 200 series, 14.12 AMD Catalyst Drivers

**Comment by larsiusprime** [comment] 2015-03-31 19:50
Hmmm, not a bad guess. The white rectangle itself is something I am
explicitly drawing, though, as a test to make sure that the window
resolution is properly within the boundaries of what's shown.

So maybe we can try this next --

- Start game in some resolution (fullscreen, whatever).
- Go to video options menu, note if there's artifacts
- Select any windowed video option smaller than the current resolution
- Note if there's artifacts
- Click okay and accept this resolution
- After the change, go back to the video menu
- Note if there's artifacts

I'm trying to test if the artifacts are tied to a specific resolution for
you, or whether they only show up when you first "change" the window and
you get that preview before you hit accept and the app reboots itself.

On Tue, Mar 31, 2015 at 2:44 PM, Rythe <notifications@github.com> wrote:

> All resolutions. Some resolutions are just cleaner about it than others.
>
> I am not able to manually resize a window.
>
> I sliced down a screenshot to just the rendering area (no window frame),
> and it was the appropriate 1600x900, which is the resolution the last set
> of screenshots came from I think.
>
> As an experiment with the resizing, I tried fullscreen 1920x1080, and
> everything was good except the game select/options windows, the naming Azra
> interface, and the Psi/HP numbers and text in battle.
>
> ...I might have just figured it out. Or at least part of it. When you
> click options, a clean and correct scroll window pops up for the various
> options. But when you then select 'Video' options, a white frame is drawn
> around the borders of the rendering area, and said video options are all
> sorts of messed up. It's probably the video options screen getting shrunk 4
> pixels each dimension without any proper scaling going on.
>
> [image: whiteframe]
> <https://cloud.githubusercontent.com/assets/11690153/6927637/45800ea0-d7b4-11e4-9781-3a98be3aa02d.png>
>
> But to restate my vid card - Radeon R9 200 series, 14.12 AMD Catalyst
> Drivers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/271#issuecomment-88223302>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Rythe** [comment] 2015-03-31 19:51
And I just realized that some of those other options without the white rectangle have garbled text, so nevermind on that guess!

**Comment by larsiusprime** [comment] 2015-03-31 19:54
I'm wondering if some of this won't go away if we add ANGLE support to the
underlying rendering system. Radeon cards sometimes have weird issues with
pure OpenGL

On Tue, Mar 31, 2015 at 2:51 PM, Rythe <notifications@github.com> wrote:

> And I just realized that some of those other options without the white
> rectangle have garbled text, so nevermind on that guess!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/271#issuecomment-88225896>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Rythe** [comment] 2015-03-31 20:13
Yeah, Radeon cards sometimes have weird issues. <.<

Although, as I'm flipping through things, I'm curious if the 'Tips and Tricks' window and subitems goes through a slightly different rendering process than the options screens.

Because I just went through 90% of the resolution options, and while lots of things have various levels of issues (even the options list window), it didn't...until 1067x600. But I blame the '67' there.

I'm curious if the 'Tips and Tricks' gets rendered and ready before the 9-slice-scaling happens while other interface things miss the buss sometimes?

Another example is that while the buttons on the basic overworld map interface looked right over 90% of the resolutions, the scrap count number sometimes didn't. That could be another thing that missed the scaling buss?

**Comment by ManDude** [comment] 2015-03-31 23:26
I can't get that graphical glitch no matter how hard I try, so yeah it must be something with your graphics card, make sure you have the drivers fully updated?

Oh and @larsiusprime , it would be good if you worked on the auto-update feature in the future so people don't have to download 500MB of data every week. But it's fine for me, I mean I download at ~1MB/sec, heh. Would still be cool (and also make sure it directly replaces old files with new files, not download an installer you have to run yourself, that's not very safe, at least it's not like those CNet installers that install virus on your computer).

**Comment by Rythe** [comment] 2015-04-01 02:17
I'd be more willing to concede that it's a problem with my card in specific except that this issue is very consistent and specific for me.  It'd be one thing if all the text was garbled, or if the text was randomly garbled, but from what I've seen, it's very consistent in the items effected and the way that those items are effected at specific resolutions.  That suggests it's not a glitch in my hardware, but a specific outcome based on software instructions.

It also suggests that certain UI items are handled differently than other UI items in the rendering/writing process.

I mentioned Factorio and Tales of Maj'Eyal earlier in part because those are 2D games too, but also because they're 2D games that I can resize on the fly without these issues. Tales appears to be an OpenGL game as well.

And my Radeon drivers said they were up to date when I checked them before. That's not to say it isn't Radeon drivers at fault, or that it's not my card in specific, but still, it doesn't seem likely given what I know and have seen at this point.

**Comment by Rythe** [comment] 2015-04-12 21:40
I didn't see the 'maybe we can try this next' beneath the ellipses forward/quote whatever in that one comment of yours until I read the email version, Lars, so! Let me go through that for whoever.

- Start game in some resolution (fullscreen, whatever): 1600x900 Windowed

- Go to video options menu, note if there's artifacts: Yes, especially in the Video options, but a little bit in the options menu (improved?), and the button graphics for a game slot with save info, but none of the other buttons or text in the game select screen.

- Select any windowed video option smaller than the current resolution: 1280x720 Windowed
- Note if there's artifacts: Yes, but there's a very brief moment during the initial resolution swap (prior to accept & reload) where the font for the resolution options is displayed correctly.

Note pretty resolution size font and oversized background -
![rezswapgood](https://cloud.githubusercontent.com/assets/11690153/7107606/ab82667e-e12f-11e4-8ac7-a264646b63aa.png)

It's still weird if you look closely at the resolution, tho'.  The first half is like 12 point font then after the 'x' it shifts down to 11 or 10 point font on many of them. So '854 x' @12pt then '480' @10pt.

Then we're back to normal (not good) -
![rezswapbad](https://cloud.githubusercontent.com/assets/11690153/7107618/385acc62-e130-11e4-8db3-e0548a2435a6.png)

- Click okay and accept this resolution: 1280x720 Windowed
- After the change, go back to the video menu
- Note if there's artifacts:

And everything is worse, but worse in a way that lead me to a theory.
![allbad](https://cloud.githubusercontent.com/assets/11690153/7107663/d6b6092a-e131-11e4-8e70-6e122ce5eac8.png)

See the zero I pointed out? The top slice of it is being rendered at a different size than the rest of it.  Which is how I noticed the font being different sizes in the video resolution options during that brief switch moment where it rendered clean.  My new theory is your 9-slice resizing thing is putting things together with pieces rendered at different resolutions. Why it's only doing that for my machine I have no idea, but that's what it looks like. It would explain the button and font artifacts I'm seeing, although maybe not the radio button ones.

**Comment by Rythe** [comment] 2015-04-12 22:16
The other thing of note is that this is only really happening with UI elements.  Backgrounds don't have this issue, and neither does the FPS count in the top right of the screen, nor the 'Loading...' part of the text on game load and reload whereas the 'x / 9 Tasks Complete' text does have issues (mostly at smaller resolutions).

**Comment by Rythe** [comment] 2015-04-12 22:29
And just for fun, I tried to see what I would have in that brief resolution swap moment going from smaller to larger. Which is to say, I got to see a clear line where slices were made to overlap rather than butted up side-by-side properly.  Sadly, I don't know if any of this counts, given its just a brief moment in the middle of a resolution change.

![overlap](https://cloud.githubusercontent.com/assets/11690153/7107871/1b01f790-e139-11e4-9c67-1d01659636a2.png)

**Comment by Rythe** [comment] 2015-04-12 23:17
Then decided to try my laptop to see if it was just my desktop.

DefQ1 0.1.2 Build 15, Win 8.1
Geforce GTX 850M (Drivers maybe 2 months out of date)

Windowed 800x600
![laptop](https://cloud.githubusercontent.com/assets/11690153/7108049/e282d572-e13f-11e4-8c4e-ba98773964d1.png)

Windowed 1600x900
![laptop2](https://cloud.githubusercontent.com/assets/11690153/7108058/fdaa6bd0-e13f-11e4-8e8d-ae1eb913b04f.png)
![laptop3](https://cloud.githubusercontent.com/assets/11690153/7108070/1bad9b66-e140-11e4-8df7-0ec6f344d6cf.png)

So chances are, this is a real problem.

**Comment by larsiusprime** [comment] 2015-04-13 22:33
As far as I can tell this looks related to a general OpenFL/Flixel interaction that I've just noted somewhere else:
https://github.com/openfl/openfl/issues/594#issuecomment-92492628

**Comment by larsiusprime** [comment] 2015-05-11 21:01
I think I finally got a lead on this.

![glitchb](https://cloud.githubusercontent.com/assets/739064/7574927/9e5a69c8-f7f6-11e4-95f3-c97cd7af5e5b.png)

Alright, so that's clearly the artifacting we've been seeing. I strongly suspected in this case the error was that the image was being drawn on a non-whole-number x/y coordinate. Sure enough, the debugger confirms that information as it's calculating a variable coordinate based on the size of the screen and I forgot to set a round on it.

But just to be sure I open up the debugger and dump the bitmap cache to see if the source image is mangled before its even drawn. Yup, it's fine in the cache. It's only mangled when placed in the game.

![glitchc](https://cloud.githubusercontent.com/assets/739064/7574948/d3c1f540-f7f6-11e4-99ae-684ccff61b30.png)

This glitch was 100% reproducible for me at 1280x720. So I force the position to an int in the map preview popup code. Afterwards:

![glitcha](https://cloud.githubusercontent.com/assets/739064/7574971/f510fcaa-f7f6-11e4-92e9-d1510b0925af.png)

Bada-bing. So if this is true, then this issue can be fixed anywhere it's seen by simply rounding the x/y coordinate of the object to the nearest integer.

**Comment by larsiusprime** [comment] 2015-05-11 21:09
For verification purposes, after the next nightly build goes out (DQ will be v 0.1.4), let me know if you see any of the artifacts *on the casual-sized star selecter outline graphic* in any of the various resolutions.

If you can't reproduce it, then given my clean before-and-after fix, it's probably the root of our cause and isn't anything weird or subtle like graphics card drivers. After that we can just start knocking out cases one by one as we notice them.

**Comment by Rythe** [comment] 2015-05-12 01:14
I'll make a note to check it, although it'll have to wait for a windows build as that's what I run. Haven't seen a new one of those in over a month, although Linux has seen more than a few.

**Comment by larsiusprime** [comment] 2015-05-12 01:20
Wait, windows hasn't been building? I'll check back in on the build server.

On Mon, May 11, 2015 at 8:14 PM, Rythe <notifications@github.com> wrote:

> I'll make a note to check it, although it'll have to wait for a windows
> build as that's what I run. Haven't seen a new one of those in over a
> month, although Linux has seen more than a few.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/271#issuecomment-101086479>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Rythe** [comment] 2015-05-12 15:04
Heh, I was wondering if that might be the disconnect, but I mentioned it before.  

You are still posting them to google drive, too? Or did you get around to using something else and I missed the memo while finishing my animated sorta text adventure webpage?

**Comment by Rythe** [comment] 2015-05-13 17:55
So, is it a problem with the build server, or me?

Because in the google drive folder, I see Win 0.1.2 build 15, Mac 0.1.2 build 17, and Linux 0.1.3 build 8 with it having the last update as of Apr 30.

**Comment by meganbednarz** [comment] 2015-08-05 02:37
I can confirm I'm still getting some ... what looks like vertical shearing where pixels are duplicated on Azra's sprite in the naming screen, and a few other places. Resolution 1280 x 720 windowed. Using Windows 7 x64, graphics card Nvidia GeForce GTX 260.

**Comment by larsiusprime** [comment] 2015-08-05 02:41
screenshot?

I thought I had this one nipped. Latest build, too?

On Tue, Aug 4, 2015 at 9:37 PM, Megan Bednarz <notifications@github.com>
wrote:

> I can confirm I'm still getting some ... what looks like vertical shearing
> where pixels are duplicated on Azra's sprite in the naming screen, and a
> few other places. Resolution 1280 x 720 windowed. Using Windows 7 x64,
> graphics card Nvidia GeForce GTX 260.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/271#issuecomment-127822766>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by meganbednarz** [comment] 2015-08-05 02:48
https://www.dropbox.com/s/aj0vf68nqx5bjbn/0.1.9-35_AzraShear.png?dl=0

**Comment by larsiusprime** [comment] 2015-08-05 03:05
Huh, that's definitely "graphical shearing" but I wonder if it's a scaling artifact with a different cause. I'll see if I can repro.

**Comment by meganbednarz** [comment] 2015-08-05 03:14
It's also happening on the "you got new skill" screen 
![0 1 9-35_azrashear_lightning](https://cloud.githubusercontent.com/assets/597059/9077642/1a4a1b4a-3af6-11e5-994c-46828e2410c6.png)

**Comment by IBwWG** [comment] 2017-01-22 13:32
2.1.2c - itch, Linux Mint 18.1 x64, HD mode@1920x1080 fullscreen

Still getting this issue, but only here and there.  E.g. see the difference between these two screens, one after the other on the same machine with the same settings:

![dq-font-ok](https://cloud.githubusercontent.com/assets/16719964/22182839/a9d41e90-e0af-11e6-8638-67e479cc9349.png)
![dq-font-shear](https://cloud.githubusercontent.com/assets/16719964/22182840/a9d48c4a-e0af-11e6-8905-bdc031eb3353.png)

**Comment by IBwWG** [comment] 2017-01-22 13:34
In this particular scene (also after the background change), Ketta's dialog is flawless, but Azra's *always* has shearing.

**Comment by IBwWG** [comment] 2017-01-22 13:35
Wrenna and Niru's speech is also OK.

**Comment by IBwWG** [comment] 2017-01-22 13:38
I'm not sure if it makes a difference, but the full screen is on an external second display.

**Comment by IBwWG** [comment] 2017-01-22 13:48
Found another spot: always (and only) the word REWARDS on the bonus level subdialog:

![dq-font-bad2](https://cloud.githubusercontent.com/assets/16719964/22182930/c212d652-e0b1-11e6-9999-4b33e8c11d08.png)

**Comment by IBwWG** [comment] 2017-01-22 14:01
In the scene "Against the Odds" (Act I, Scene IV), Ozimal always shears, but the guard never does.  It seems to be consistent with a given character in a given scene, so far.

**Comment by ManDude** [comment] 2018-01-10 00:56
Closing this issue since it was messing with the progress tracker on the site.

It's probably better to report stuff like these (if any are found) under new issues.

**Closed by ManDude** 2018-01-10 00:56 UTC
Labels: 1, DQ CORE, bug
