### ISSUE TITLE
Game crashes when casting Etherflash

### ISSUE THREAD

**Issue by dqhdbughunter** [larsiusprime/tdrpg-bugs#1065] opened 2016-06-16 08:16 UTC
BASIC INFORMATION:

Operating System: Linux i686
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : 2.0.0

STEPS TO REPRODUCE:
1. Boost a healer with Etherflash to boost level 2
2. Wait for the healer to cast Etherflash

WHAT I EXPECTED TO HAPPEN:

I expected the healer to deal damage and lighten up dark enemies so that Slak could cut them down even faster.

WHAT HAPPENED INSTEAD:

The game crashed and Slak became depressed because he couldn't kill those revenant.

The crash happens reliably, independent of whether area attacks are highlighted or not. The crash seems to happen at the end of the casting animation. Usually, the game just crashes with "Floating point exception (core dumped)", but once I got this trace:

Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_backend/native/NativeApplication.hx line 368
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 761
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/DisplayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObject.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 530
Called from flixel.FlxGame::step flixel/FlxGame.hx line 663
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx line 1486
Called from flixel.FlxGame::update flixel/FlxGame.hx line 752
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 168
Called from com.leveluplabs.tdrpg.State_Battle::update com/leveluplabs/tdrpg/State_Battle.hx line 903
Called from com.leveluplabs.tdrpg.State_Battle::updateBasic com/leveluplabs/tdrpg/State_Battle.hx line 951
Called from com.leveluplabs.tdrpg.BattleField::update com/leveluplabs/tdrpg/BattleField.hx line 884
Called from flixel.group.FlxTypedGroup::update flixel/group/FlxGroup.hx line 138
Called from flixel.group.FlxTypedGroup::update flixel/group/FlxGroup.hx line 138
Called from com.leveluplabs.tdrpg.CreatureSprite::update com/leveluplabs/tdrpg/CreatureSprite.hx line 1768
Called from com.leveluplabs.tdrpg.TDRPGEntitySprite::update com/leveluplabs/tdrpg/TDRPGEntitySprite.hx line 100
Called from flixel.FlxSprite::update flixel/FlxSprite.hx line 586
Called from com.leveluplabs.tdrpg.CreatureSprite::updateAnimation com/leveluplabs/tdrpg/CreatureSprite.hx line 590
Called from com.leveluplabs.tdrpg.TDRPGEntitySprite::tdrpgUpdateAnimation com/leveluplabs/tdrpg/TDRPGEntitySprite.hx line 88
Called from flixel.editors.EntitySprite::updateAnimation flixel/editors/EntitySprite.hx line 746
Called from flixel.FlxSprite::updateAnimation flixel/FlxSprite.hx line 594
Called from flixel.animation.FlxAnimationController::update flixel/animation/FlxAnimationController.hx line 88
Called from flixel.animation.FlxAnimation::update flixel/animation/FlxAnimation.hx line 224
Called from flixel.animation.FlxAnimation::set_curFrame flixel/animation/FlxAnimation.hx line 268
Called from flixel.animation.FlxBaseAnimation::set_curIndex flixel/animation/FlxBaseAnimation.hx line 33
Called from flixel.animation.FlxAnimationController::set_frameIndex flixel/animation/FlxAnimationController.hx line 733
Called from flixel.editors.EntitySprite::animationCallback flixel/editors/EntitySprite.hx line 885
Called from com.leveluplabs.tdrpg.DefenderSprite::onSweetFrame com/leveluplabs/tdrpg/DefenderSprite.hx line 645
Called from com.leveluplabs.tdrpg.DefenderSprite::launchAttack com/leveluplabs/tdrpg/DefenderSprite.hx line 2719
Called from com.leveluplabs.tdrpg.DefenderSprite::doSplash com/leveluplabs/tdrpg/DefenderSprite.hx line 3141
Called from com.leveluplabs.tdrpg.BattleModel::fireSplash com/leveluplabs/tdrpg/BattleModel.hx line 492
Called from com.leveluplabs.tdrpg.SplashEffect::new com/leveluplabs/tdrpg/SplashEffect.hx line 75
Called from com.leveluplabs.tdrpg.SplashEffect::setup com/leveluplabs/tdrpg/SplashEffect.hx line 316
Called from com.leveluplabs.tdrpg.Factory_Effect::getForBattle com/leveluplabs/tdrpg/Factory_Effect.hx line 141
Called from com.leveluplabs.tdrpg.Factory_Effect::get com/leveluplabs/tdrpg/Factory_Effect.hx line 153
Called from com.leveluplabs.tdrpg.Factory_Effect::getSub com/leveluplabs/tdrpg/Factory_Effect.hx line 238
Called from com.leveluplabs.tdrpg.Effect::recycle com/leveluplabs/tdrpg/Effect.hx line 53
Called from com.leveluplabs.tdrpg.Effect::setup com/leveluplabs/tdrpg/Effect.hx line 85
Called from com.leveluplabs.tdrpg.TDRPGEntitySprite::loadEntityGraphics com/leveluplabs/tdrpg/TDRPGEntitySprite.hx line 78
Called from flixel.editors.EntitySprite::loadEntityGraphics flixel/editors/EntitySprite.hx line 189
Called from flixel.FlxSprite::loadGraphic flixel/FlxSprite.hx line 343
Called from flixel.FlxSprite::set_frames flixel/FlxSprite.hx line 1258
Called from flixel.FlxSprite::set_frame flixel/FlxSprite.hx line 1132
Error : Null Object Reference

**Comment by larsiusprime** [comment] 2016-06-16 14:49
Thanks for the stack trace, I'll do my best to fix this right away.

**Comment by dqhdbughunter** [comment] 2016-06-16 18:40
The game also crashes when casting holy light.

However, when switching to the original sprites, everything works fine.

**Comment by larsiusprime** [comment] 2016-06-20 20:31
Been trying to reproduce this for a while and can't quite get it. Do you have a save file you can share?

**Comment by dqhdbughunter** [comment] 2016-06-20 20:53
I was playing the game on my desktop computer when I had the crashes. I just tried the save on my laptop, and everything works fine. So a save file is probably not going to help debug this problem.

What I know right now:
desktop (crashes every single time on casting etherflash or holy light, only on hd sprites):
Xubuntu 14.04 LTS, using the i686 version of DefendersQuest

laptop (no crashes):
Debian 8.3 (Jessie), using x86_64 version of DQ


If I find the time I will try to find more conditions for this crash (probably going to try a newer version of Xubuntu first). If you want me to test something specific, don't hesitate to let me know.

**Comment by larsiusprime** [comment] 2016-06-20 21:05
Cool, so it looks like just the desktop then, and on Linux? I wonder if it's related to video drivers or something, though I don't know why etherflash in particular would trigger it. If you dial down the particle count in the video menu to 0, does it still crash on your desktop?

**Comment by dqhdbughunter** [comment] 2016-06-20 22:03
ok, so I did a couple of tests with interesting results:
- particle count does not affect crashing or not crashing
- resolution of the game window does affect the crash!
- I could not get a crash with my laptop (using the same external monitor as the desktop, so the same resolutions)
- fullscreen (1920x1200) did not crash, but all menu backgrounds are missing (laptop and desktop)
- I could not get a crash with the original sprites, only ever with hd sprites
- On the desktop, I noted 3 different behaviours:
(1) no crashes: widescreen 1366x768, 1280x720 and 4:3 1400x1050, 1280x960, 1024x768
(2) crashes when selecting any defender to place on the battle field: widescreen 1600x900, 1142x648 and 4:3 1152x864. The message is "Floating point exception (core dumped)", no trace
(3) crashes when casting etherflash: widescreen 1704x960, same trace as in the first post

So it appears that in the end this bug is related to the resizing of the sprites. Some other people seem to have had similar issues. It is still weird that I can't reproduce this on the laptop. Maybe the different behaviour at different resolutions helps to find the problem. Let me know if I can test anything else.

**Comment by larsiusprime** [comment] 2016-06-21 14:20
@dqhdbughunter -- have you tried a later version of the game? Where did you get the game from? We've put out a few patches since 2.0.0 already, Humble, GOG, and Steam should all be up to at least 2.0.2a by now, and 2.0.3 is up on a steam beta channel as of last night.

**Comment by larsiusprime** [comment] 2016-06-22 03:06
@dqbughunter:

2.0.3a is up on test_public now, this includes improvements specifically to effects like ether flash. Let me know if it does any better?

**Comment by dqhdbughunter** [comment] 2016-06-24 14:05
ok, I installed 2.0.3a. I had very little time, but still get crashes as described in (2) above (crashing when selecting any defender). Have had no crashes on casting Etherflash yet, but have to do some more tests next week (will be away from desktop during the week-end), will report back after the tests.

**Comment by larsiusprime** [comment] 2016-06-24 22:45
2.0.4c is up now

**Comment by larsiusprime** [comment] 2016-06-29 19:22
2.0.5c is up now

**Comment by dqhdbughunter** [comment] 2016-06-29 20:55
still 2.0.3a on humblebundle (linux version)

**Comment by larsiusprime** [comment] 2016-06-30 18:32
2.0.5c should be up on humble now

**Comment by dqhdbughunter** [comment] 2016-06-30 20:42
ok, I tested version 2.0.5c.
- no crashes at all when casting etherflash

- I still get crashes on some resolutions when selecting any defender to place on the battlefield ("floating point exception (core dumped)")

crashes happen on the following resolutions:
  1920x1200 windowed and fullscreen
  1600x900
  1152x648
  1152x864

I tested all resolutions, namely:
  wide: 1152x648, 1280x720, 1366x768, 1600x900, 1704x960, 1920x1080, 1920x1200
  standard: 800x600, 1024x768, 1152x864, 1280x960, 1400x1050, 1600x1200

**Comment by larsiusprime** [comment] 2016-06-30 20:51
That's so strange, thanks for the report. I'll try to reproduce it if I
can. Glad that at least some crashes are gone.

This is only on linux, yes?

**Comment by larsiusprime** [comment] 2016-06-30 20:53
Oh! There should be a crashdump folder in your game's save files.

If you click the floppy disk icon on the save slot screen, it will take you
to your save files. Look for a folder called "log" and if its there, look
in the most recent subfolder, and tell me what the contents of _error.txt
are?

On Thu, Jun 30, 2016 at 3:49 PM, Lars Doucet <lars.doucet@gmail.com> wrote:

> That's so strange, thanks for the report. I'll try to reproduce it if I
> can. Glad that at least some crashes are gone.
>
> This is only on linux, yes?
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by dqhdbughunter** [comment] 2016-06-30 21:15
I found the save game folder as you described, but there is no log subfolder, only 4 xml files and the dfq save file.

This is on linux, yes, the only operating system I have. I should probably retry on a newer version of xubuntu and possibly with different video drivers, but I won't have the time soon. By the way, the title screen now states "Hardware + OpenGL". As already stated earlier, I have no crashes on my laptop running Debian, using the same external monitor and the same save file. In a way I am having trouble reproducing this crash myself :/

**Comment by larsiusprime** [comment] 2016-06-30 21:23
Hmm, weird that crashdumper isn't kicking in. Thanks for the report, I'll
try to reproduce myself until we get to the bottom of this.

On Thu, Jun 30, 2016 at 4:15 PM, dqhdbughunter <notifications@github.com>
wrote:

> I found the save game folder as you described, but there is no log
> subfolder, only 4 xml files and the dfq save file.
>
> This is on linux, yes, the only operating system I have. I should probably
> retry on a newer version of xubuntu and possibly with different video
> drivers, but I won't have the time soon. By the way, the title screen now
> states "Hardware + OpenGL". As already stated earlier, I have no crashes on
> my laptop running Debian, using the same external monitor and the same save
> file. In a way I am having trouble reproducing this crash myself :/
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1065#issuecomment-229791022>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-Gp-Ubl-W9kNoy_i-pxxRdGj3a-xks5qRDHYgaJpZM4I3Igb>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment] 2016-07-01 04:55
The Crash dumper is disabled by default. Enable it in the options menu (Options > Logging).

**Comment by dqhdbughunter** [comment] 2016-07-01 06:51
nice catch, logging wasn't enabled.
But even with logging enabled I don't get a crash dump (not in the settings directory, not in the game directory).

**Comment by ManDude** [comment] 2016-07-01 13:03
Did you check every checkbox in the logging menu?

**Comment by dqhdbughunter** [comment] 2016-07-01 13:05
I just tried it again, with all checkboxes checked. Same crash, no crash log.

**Comment by larsiusprime** [comment] 2016-07-01 14:27
Weird. Maybe it only works on certain OS'es.

On Fri, Jul 1, 2016 at 8:05 AM, dqhdbughunter <notifications@github.com>
wrote:

> I just tried it again, with all checkboxes checked. Same crash, no crash
> log.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1065#issuecomment-229941454>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-Dm_HKPJC6VXg6p6ckW1GbhzSBQ9ks5qRRC2gaJpZM4I3Igb>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment] 2016-11-11 17:06
Closing for now until I get more reports that this is still happening in the latest version of the game.

**Closed** 2016-11-11 17:07 UTC
Labels: 1, Battle, bug, DQ CORE, Priority HIGH
