### ISSUE TITLE
Azra takes damage on mini-indicator but not in sidebar

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#716] opened 2016-04-29 08:06 UTC
0.5.7win7x64

A few times, I noticed when an enemy got in, her sidebar health flashed down a second and then back up to full.

![dq-azra-damage](https://cloud.githubusercontent.com/assets/16719964/14910941/141c3c38-0df2-11e6-8cbe-ab803628fff1.png)

At the end of the battle, it said she survived but with injuries; at this point the sidebar was still showing 255/255.

**Comment by larsiusprime** [comment] 2016-04-29 18:51
Strange... this isn't easy to reproduce, so it might be the result of a cascading bug, where some other bug causes an execution step to short circuit so that it doesn't get around to updating her health any more. Were there any other problems in this level?

**Comment by IBwWG** [comment] 2016-04-29 18:57
Just the other ones I reported around then...wrong "WAIT" etc. cursors...I forget what else if any...but, I do remember that I had this on more than one run-through on this level.  I thought I had gotten a perfect run the second time, but it said I hadn't.

**Comment by larsiusprime** [comment] 2016-05-02 20:05
Okay, so in 0.5.8+ does this still happen? Pretty sure it was a result of the "double Azra" symptom. Double-Azra was caused by playing any battle and then restarting it and using the battle layout (even an "empty" one).

**Comment by IBwWG** [comment] 2016-05-03 06:01
0.6.0.win7x64, HD mode@1704x960windowed

I haven't seen it on the few tests I've done so far.

**Comment by larsiusprime** [comment] 2016-05-03 13:33
Let's close it for now unless it resurfaces as we have a strong logical reason basis to believe it is fixed. On the off chance it isn't, it should re-appear by itself eventually while we're testing other things.

**Closed by larsiusprime** 2016-05-03 13:33 UTC
Labels: 1, bug, DQ CORE, Please Verify, Priority HIGH
