### ISSUE TITLE
Need to work on ET tutorials + UX notifications

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#735] opened 2016-05-01 14:48 UTC
0.5.7, not sure if this was an intentional effect or not:

![dq-many-health-bars](https://cloud.githubusercontent.com/assets/16719964/14942405/81a97592-0fbc-11e6-852c-95e7e5b202d6.png)

**Comment by larsiusprime** [comment] 2016-05-02 16:09
Absolutely. Does the tutorial show up for you explaining what's happening?

**Comment by IBwWG** [comment] 2016-05-02 16:35
My bad, I forgot I had turned the tutorials off!  That would probably help with that level, because if it weren't for the crashing and me eventually just using F2 to pass it, I would have remained confused as to what was happening.  Will try again!  :)

**Comment by larsiusprime** [comment] 2016-05-02 20:11
Actually, can you test it again with tutorials OFF?

It's important enough information that we actually *force* the tutorial here, because otherwise players will get confused as to what's happening. If the tutorials are off but you're *still* not seeing a tutorial explanation, then that's a legit bug. I just wanted to know if it popped up and you instinctually closed it or something, which would indicate I need a UX tweak.

**Comment by IBwWG** [comment] 2016-05-02 20:15
Come to think of it, there were a few lines of tutorial despite my setting.  Or dialog.  I'm not sure the difference sometimes.  Anyway, Z said a few things and A did too, including something about "he's under some kind of protection".  That didn't quite explain the multiple health bars to me, was it meant to?  Anyway I'll give it another shot when I get a chance.

**Comment by larsiusprime** [comment] 2016-05-02 20:27
Yeah, thought so. This isn't the first time we've heard that. I think I
need some kind of feedback in the mission itself that isn't just in a
pop-up. Basically, Eztli has several forms, each tied to a unique health
bar. Once you've whittled down one health bar, you have to *boost Azra*
(you can only do this in the final battle) to unlock the next one. When
that one's whacked, then he goes to his next form and you have to do it
again, etc.

I probably should put some kind of special sound effect or VFX on eztli
when you're whacking him when his barrier is up, and put a bouncing arrow
or something next to Azra signalling that you need to boost her to punch
through it.

On Mon, May 2, 2016 at 3:15 PM, IBwWG <notifications@github.com> wrote:

> Come to think of it, there were a few lines of tutorial despite my
> setting. Or dialog. I'm not sure the difference sometimes. Anyway, Z said a
> few things and A did too, including something about "he's under some kind
> of protection". That didn't quite explain the multiple health bars to me,
> was it meant to? Anyway I'll give it another shot when I get a chance.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/735#issuecomment-216349813>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment] 2016-05-03 04:59
Oh OK, I totally didn't get that.

I just tried on Advance, with tutorials and dialog both set to "never".

1) around the first wave ET fills the screen with purple clouds.  not sure what that was about.  didn't see any numbers with it...no effect?
2) the attackers sometimes have speech bubbles with an Azra icon, I guess that tells you which way they're going.  Cool.
3) I attacked ET with defenders.  On the first hit, the multiple health bars appeared.  After a while I whittled down his first form and now he's Level 7 and invincible.  No tutorial came up.

**Comment by IBwWG** [comment] 2016-05-03 05:05
OK, now with the tutorials and dialog on Always it makes more sense.  However, I don't believe the first run through I saw the tutorial "Azra herself can be boosted".

**Comment by IBwWG** [comment] 2016-05-03 05:07
Also the whole battlefield seems to have a permanent (but sometimes changing in intensity) white overlay.  Is that just ET's area attack highlighted?

**Comment by larsiusprime** [comment] 2016-05-03 13:37
The white overlay should only appear when ET is casting a spell, and you can configure its visibility in the menu. It should disappear when the spell is over. 

The purple clouds should be doing damage, and the tutorials should always be appearing no matter what. I'll investigate.

**Comment by IBwWG** [comment] 2016-05-03 14:22
The white overlay, I'm not 100% sure whether it was there at the beginning, but after reporting this it stayed until the end, and only got temporarily stronger whenever Zelemir struck with lightening.  By configure in the menu do you mean the general "area attacks"?

**Comment by larsiusprime** [comment] 2016-05-03 15:36
Yeah, you can turn it off. It makes it easier to know exactly what the size and shape of area effect attacks is, but it's optional. I also suspect it's the cause of the memory leak, if you see my recent comments on that other bug.

**Comment by ManDude** [comment] 2016-05-28 00:12
If you click Eztli-Tenoch and check his spells, it will say his Dragon Fire will deal 0 HP damage.

**Comment by IBwWG** [comment] 2016-06-05 18:42
Just ran "the way out" on NG, and the tutorial appeared correctly (i.e. despite my "new battles only" setting)

**Comment by larsiusprime** [comment] 2018-06-21 15:15
This should be fixed now

**Closed by larsiusprime** 2018-06-21 15:15 UTC
Labels: 1, Battle, DQ CORE, Priority MID, ready
