### ISSUE TITLE
Crash when clicking on berserker's skills

### ISSUE THREAD

**Issue by beittenc** [larsiusprime/tdrpg-bugs#1048] opened 2016-06-15 16:15 UTC
Operating System: Windows 10
Browser/Download: Download (Steam)
Demo/Full?      : Full Version
Version #       : Steam DQ1 2.0.0
Optional Info: I'm doing a named hero only play, but not in hero mode, so this applies to the default berserker (Slak?)

Steps to Reproduce:

1. Have a berserker who has leveled up and has skills to assign.
2. From the main menu, click on Party
3. Click on the berserker
4. Game crashes

WHAT I EXPECTED TO HAPPEN:

I see the lovely skill screen for my character

WHAT HAPPENED INSTEAD:

The game crashes almost every time.

I am able to reproduce this pretty consistently. It doesn't matter if I go to the screen immediately after a battle (when he levels up) or from the party screen. It happens if I click on his first or click on other party members and then the berserker's.

In case it's useful, I'm attaching an export of my save.
[crashing save.zip](https://github.com/larsiusprime/tdrpg-bugs/files/316610/crashing.save.zip)

**Comment by ManDude** [comment] 2016-06-15 16:21
What language were you playing at?

**Comment by larsiusprime** [comment] 2016-06-15 17:27
@ManDude: can you elaborate on the reproduction process? I can't quite get it yet.

**Comment by ManDude** [comment] 2016-06-15 17:36
> Start a new game (set XP gain to 300% to speed things up)

> Complete first then second battle

> Proceed through the berserker level up tutorials until you get the opportunity to leave the party screen (which is before the part where you have to click on a skill to upgrade). Leave the party screen.

> Enter Party screen from the overworld. Upgrading a berserker's skills will crash the game with a Null Object Reference error.

**Comment by beittenc** [comment] 2016-06-15 17:41
US English

**Comment by beittenc** [comment] 2016-06-15 18:10
Sorry for the delay in response. It sounds like you have the steps to reproduce, @ManDude. I believe those match what I did initially (or are pretty close), but now I crash every time I just try to go to the berserker's skill screen; I don't even get a chance to click on a skill. I was able to get at least one skill upgraded yesterday, but today he doesn't like me.

**Comment by ManDude** [comment] 2016-06-15 18:13
I relaunched the game and I can add skill points now. Hm.

**Comment by beittenc** [comment] 2016-06-15 18:24
I definitely crash to desktop every time. I can try and record a video if you want. Or if there's something else you'd like me to try, I'm happy to do so.

**Comment by larsiusprime** [comment] 2016-06-15 18:59
Yeah, if you can record a video of it happening, that would be great.

Another thing you can try is running the game from the command line, that will sometimes output a stack trace that usually isolates the bug.

Try this: right click the game in steam, go to properties, then local files, then "browse local files" to get the game directory.

If you navigate there with cmd.exe and run DefendersQuest.exe (the one in the "dx" folder, mind you, the other one is the legacy version), that should do it.

**Comment by larsiusprime** [comment] 2016-06-15 19:01
I'm going to try to reproduce anyways, but if that doesn't work, please do try the command line thing.

**Comment by larsiusprime** [comment] 2016-06-15 19:04
Hmmm, can't reproduce. I wonder if I'm missing some step (like leave the party screen before the level up animation finishes, or something).

**Comment by ManDude** [comment] 2016-06-15 19:07
Lemme try to record a video real quick.

**Comment by ManDude** [comment] 2016-06-15 19:11
Weird, I couldn't reproduce it either. Hm.

**Comment by beittenc** [comment] 2016-06-15 19:23
Working on getting ShadowPlay up and running so I can record a video. I can definitely reproduce consistently. After that, I'll try the direct executable method.

**Comment by larsiusprime** [comment] 2016-06-15 19:23
Thanks very much @beittenc, so sorry about this trouble. I really appreciate your patience and willingness to help us narrow down the issue.

**Comment by beittenc** [comment] 2016-06-15 19:28
@larsiusprime - No worries. I'm a developer too, so I know how frustrating these sorts of things can be. Plus this is one of my favorite tower defense games, so I'm happy to help.

Here's a video I recorded of the crash. It's pretty short and doesn't show anything except my opening the game, running through the steps, and crashing. If you want to see more, let me know. I've set the video as unlisted on Youtube so hopefully it won't show up associated with the game.

https://youtu.be/kNArqdT2rAM

Off to try the other method now.

**Comment by beittenc** [comment] 2016-06-15 19:31
Same crash running through the command line. Here's the debug output it sent; hopefully it's more useful to you than it is to me.

E:\SteamLibrary\steamapps\common\DefendersQuest\dx>FlxUIButton name = movies_btn
FlxUIButton name = music_btn
FlxUIButton name = sfx_btn
FlxUIButton name = party_btn
FlxUIButton name = btn_journal
FlxUIButton name = btn_town
FlxUIButton name = tips_btn
FlxUIButton name = btn_battle
FlxUIButton name = exit_btn
FlxUIButton name = options_btn
FlxUIButton name = menu_btn
FlxUIButton name = bonus_btn

**Comment by larsiusprime** [comment] 2016-06-15 19:41
Hmmm, that's all it printed? Must be a hard crash then.

**Comment by larsiusprime** [comment] 2016-06-15 19:42
Whoooooa what kind of resolution is that? Super widescreen! I wonder if that's the problem. What happens when you try in windowed mode at a 16x9 resolution?

**Comment by beittenc** [comment] 2016-06-15 19:49
It's ultra widescreen; 2560x1080. I initially discounted the resolution because the other skills work fine, but I'll try dropping it to a 16x9 and seeing what happens.

**Comment by larsiusprime** [comment] 2016-06-15 19:50
It would be weird if that's what's going on as it's also affecting ManDude intermittently, but we might as well test as that's the thing that's noticeably different for you.

**Comment by beittenc** [comment] 2016-06-15 19:52
Running at 1600x900 windowed did not crash. I'm going to run another couple missions and see if it happens again.

**Comment by beittenc** [comment] 2016-06-15 19:52
Stupid close and comment button.

**Comment by larsiusprime** [comment] 2016-06-15 19:54
Thanks, I bet it's caused by an edge case with the scaling logic. What I should probably do is just hard-box the party screen at 16x9 if it detects your monitor is wider than that.

**Comment by beittenc** [comment] 2016-06-15 19:56
I think that'd probably be acceptable. I usually prefer to run at fullscreen just so I don't have to worry about my mouse escaping a window, but I don't care if I have vertical bars or a limited resolution as long as it's a sane one.

**Comment by larsiusprime** [comment] 2016-06-15 19:59
Yeah, I'll look into it. Please let me know if any other screens misbehave in ultra widescreen mode.

(Can you tell I don't have such a monitor myself :P? )

- [ ] Pillarbox Party screen to 16x9 max

**Comment by beittenc** [comment] 2016-06-15 20:17
Back at fullscreen (ultra wide), I also crashed trying to adjust skills on my first healer's skills (Bakal). So looks like you're right about that.

**Comment by larsiusprime** [comment] 2016-06-15 20:22
I can probably reproduce this locally when I have some time, I'd like to fix the original bug. I'll just let the game window hang off my comparatively tiny screen.

**Comment by larsiusprime** [comment] 2016-06-16 21:21
Fixed in 2.0.1 on test_public

**Closed** 2016-06-16 21:22 UTC
Labels: 1, bug, DQ CORE, in progress, Party, Priority HIGH
