### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#452] opened 2015-09-01 00:18 UTC
Just downloaded most recent build. The game crashes with the error screen after the 4th loading phase thing. It doesn't create any files for some reason too, so instead I'm posting an image.

![brmuyzx](https://cloud.githubusercontent.com/assets/7569514/9593593/538e60d4-5048-11e5-8384-b4d1230c46da.png)

For the record, I did delete the appdata folders, and manually changed locale from pt to en but it still persists.

**Comment by larsiusprime** [comment] 2015-09-02 00:53
This happens for me too; I think the problem is I have switched from the "legacy" build of OpenFL to the "next" build, but failed to update the build server.

I'm running a new build right now with the updated settings, let's see how that goes.

**Comment by larsiusprime** [comment] 2015-09-02 01:59
Should be fixed now. Try the latest build and thanks for reporting!

**Closed** 2015-09-02 02:16 UTC
Labels: 1, bug, DQ CORE

**Comment by ManDude** [comment] 2015-09-02 02:47
Assuming latest build is 0.2.1 build 3, it crashes as soon as it displays any graphic (gives the "Program stopped working" message).

**Comment by tdrpg-fan** [comment] 2015-09-02 04:14
I saw this crash as well with build 60, but the most recent build worked for me.

Currently I see the following most recent builds available in Google Drive:

# Defender's Quest I (0.2.1 build 60) 3:01 pm
# Defender's Quest I (0.2.1 build 60) 6:16 pm
# Defender's Quest I (0.2.1 build 3) 6:35 pm

Items 1 and 2 (which are both called "0.2.1 build 60") both crash for me with the error ManDude reports at the start. However, "0.2.1 build 3" works for me. I am able to start the application, load the title screen, start a new game, and play the first level.

I note that my title screen only displays a single version number though: "DQ1 0.2.1". Is that expected?

--

System Info:

Operating System: Windows 7, 32-bit
Build: 0.2.1 build 3
Game Version: DQ1 0.2.1
Screen info: Windowed mode, 800x600 (I just booted up with the defaults)

**Comment by tdrpg-fan** [comment] 2015-09-02 04:16
@larsiusprime Do you know why the builds available in Google Drive might have repeated and/or reset their build number? i.e. Any clues why we saw build 60, then 60 again, then 3? Is there a build script that changed?

**Comment by larsiusprime** [comment] 2015-09-02 11:24
So, the automated build server runs every night, or whenever I manually click the button to build instantly. A build with the same name (version number + build number) should be exactly the same as another sharing it. A build with the same version number but different build number will be different.

Basically, I update the code every day but only ocassionally get around to updating the version number, and the server builds with whatever it has. If the version number is the same but the code different, it updates the build number to note the difference.

But yesterday I was trying to repro the problem so I hit the "build now" button, and it output an identical build (a broken one). This indicated to me the problem was I hadn't switched to using the "next" settings -- it was still uploading the "legacy" build. Eventually I fixed this, and then it started uploading the fresh new build with the new build settings (and name).

**Comment by larsiusprime** [comment] 2015-09-02 11:28
And yeah, the title screen only shows one version number. It used to show both the engine version number and the game content version number, but this honestly got a little confusing. Likewise the build number is something just attached to the file for now, I'm not sure how to get the game to be able to detect that metadata and pull it into the title screen.

**Comment by tdrpg-fan** [comment] 2015-09-03 06:15
@larsiusprime Excellent, thanks for the explanation. Does this also mean that no new builds get auto-posted unless there are actual code changes made that day?

**Comment by ManDude** [comment] 2015-09-04 00:55
My "GPU" is a GM965 chipset (Intel mobile), could that be an issue?

**Comment by larsiusprime** [comment] 2015-09-04 01:06
Yeah, new builds only go up if they detect changes in the code, whether from me, or in any of the dependent libraries (openfl, flixel, etc).

@ManDude  -- weird. I would definitely like to try to investigate this if it's still happening after tonight's build. Can you send me some more specs about your machine? I'll forward them to the OpenFL team.

**Comment by ManDude** [comment] 2015-09-04 01:33
Ah, I haven't checked tonight's build yet. Will edit this post if it persists (should take less than an hour).

**Comment by larsiusprime** [comment] 2015-09-04 01:38
Tonight's build won't be up for another few hours :)

**Comment by ManDude** [comment] 2015-09-04 01:45
Well, I meant the last one (it's almost 3AM here) hehe.

**Comment by tdrpg-fan** [comment] 2015-09-04 02:48
@larsiusprime Are new automated builds posted at e.g. midnight Central time (UTC -6)?

I was trying to see if there was a way to be automatically notified/emailed when a new build was pushed to the Google Drive folder. I haven't been able to find a way - only this thread full of people asking for the feature https://productforums.google.com/forum/#!topic/drive/fsYwbZ3hpjc

**Comment by larsiusprime** [comment] 2015-09-04 03:23
I suppose I could set up my own sort of script or notification. So many things to do :)

Probably what I'll just do is figure out when the script runs and post that publicly somewhere.

**Comment by tdrpg-fan** [comment] 2015-09-04 03:30
Publicly posting the time sounds good to me. I'd rather try to make it easier for you to spend time working on the game than setting up infrastructure for me ;)

**Comment by ManDude** [comment] 2015-09-19 19:33
I'm still getting the "DefendersQuest.exe has stopped working" error with the most recent build (I'm going to check the builds before that one to see when it broke).

**Comment by tdrpg-fan** [comment] 2015-09-27 20:05
I'm now getting a crash on load using 0.2.3 build 9 on Windows 7. I'm not sure if it's the same crash as this ticket. With 0.2.3 build 9 I don't see any of the background console windows that popped up before during loading - I get a window with the title "Defender's Quest I", and then Windows immediately pops up the "this program has stopped working" dialog.

I could investigate more if you're interested, or just leave it be for a few builds if you're working on this or fixing something else anyway.

**Comment by ManDude** [comment] 2015-09-27 20:16
I'm on Windows 7 too.

**Comment by larsiusprime** [comment] 2015-09-27 20:26
Did you guys see the notice on the forum about the "MODE" builds? Does either of them work?

**Comment by ManDude** [comment] 2015-09-27 20:40
Legacy crashes after the HaxeFlixel screen, Next crashes as soon as the window opens (doesn't even display graphics, but sound works).

**Comment by larsiusprime** [comment] 2015-09-27 21:33
@tdrpg-fan , do you get the same results with the MODE demos as ManDude?

**Comment by tdrpg-fan** [comment] 2015-09-28 01:17
Both the MODE_legacy and MODE_next demos run just fine for me. They load into the game and I can run around, no crashes, and exit normally. My current Windows 7 box is 32-bit, if that means anything. If you need I could possibly set up an Ubuntu machine for testing as well (not sure if things are expected to run there).

**Comment by ManDude** [comment] 2015-09-28 08:35
Maybe some sort of update to OpenFL is causing this issue?

**Comment by larsiusprime** [comment] 2015-09-28 12:43
I don't have linux builds right this minute, but will have them in the coming weeks.

@ManDude -- if BOTH of the builds are crashing at any point, that's significant. Can you send me your system data? Since you generated a valid crash report at some time, type this into your windows explorer bar:

```%APPDATA%\LevelUpLabs\DefendersQuest\log\errors```

and hit enter. Then see if there's any folders there, open one, and look for "_error.txt". If you find that, paste the top part with System Data:

```
SystemData
{
  OS : Windows 7 SP1
  RAM: 8387064 KB (8 GB)
  CPU: Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz
  GPU: ATI Radeon HD 4800 Series, driver v. 8.970.100.1100
}
```

That way I can see if others with the same graphics card (or whatever) that you have, have the same problem or not.

**Comment by ManDude** [comment] 2015-10-03 09:39
Since I deleted everything while seeing if that was the problem, I have no crash reports. But the crashdumper didn't make any files last time it appeared anyway. So this is the specs from memory:
- OS: Windows 7 32-bit
- RAM: 1 GB
- CPU: Intel Pentium IV running at 1.46GHz (modern enough)
- GPU: Intel GM965 Express Chipset Family (ancient but modern enough too)

**Comment by larsiusprime** [comment] 2015-10-03 12:02
Cool!

I may have some leads; I'm going to update the server on monday and that might solve some of this.

Also, do you know what version of your graphics driver you're using?

**Comment by ManDude** [comment] 2015-10-03 14:26
8.15.10.1930

I think that's the most recent one.
