### ISSUE TITLE
Start Screen: Export button does not function

### ISSUE THREAD

**Issue by tdrpg-fan** [larsiusprime/tdrpg-bugs#455] opened 2015-09-02 04:28 UTC
After pressing Start on the Title screen, clicking on the 'Export' button doesn't do anything yet.

#### Repro steps:
1. Start the game after you have beaten at least the first level and saved your game (I can give a detailed breakdown of these steps if you need)
2. At the Title Screen, click Start
3. Click the 'Export' button beside your save game slot
4. The button appears to do nothing

**Expected behaviour:** The 'Export' button would open a save dialog to let me export my saved game (e.g. to help with repro steps for other bugs ;)

--
**System Info**

Operating System: Windows 7, 32-bit
Build: 0.2.1 build 3
Game Version: DQ1 0.2.1

**Comment by tdrpg-fan** [comment] 2015-09-02 04:29
Hey @larsiusprime - pardon the noise if you're not interested in this kind of feedback. Do you even want bugs like this yet?

**Comment by ManDude** [comment] 2015-09-02 12:32
Any bug should be welcome! As a temporary solution, you can go to your AppData/Roaming/LevelUpLabs folder, which contains the savefiles

**Comment by larsiusprime** [comment] 2015-09-02 13:56
Absolutely, and this is a great bug. There's always a chance I know about a bug already, but even if I do having it on my list is helpful because then it reminds me I need to fix it!

**Comment by tdrpg-fan** [comment] 2015-09-03 06:12
@larsiusprime Okay, thanks! I won't go crazy but I might file a few other issues then ;)

@ManDude Aha! Fantastic workaround - manually dumping to/from the save folder is a great idea. Kudos.

**Comment by larsiusprime** [comment] 2015-09-03 14:30
Okay, this was a regression. It'll be fixed in tonight's build.

By the way, that little button in the lower right hand corner with the wrench on it? Takes you right to your save file location, so you don't have to remember the path. Useful in case of emergencies ;)

**Closed by larsiusprime** 2015-09-03 14:30 UTC
Labels: 1, bug, DQ CORE

**Comment by tdrpg-fan** [comment] 2015-09-04 02:44
I'm guessing you mean the next build *after* 0.2.1 build 4. This does not appear to work in 0.2.1 build 4, so I'll wait for the next one :)

Thanks!

**Comment by tdrpg-fan** [comment] 2015-09-05 07:18
Confirmed fixed in 0.2.1 build 5. Thanks Lars!
