### ISSUE TITLE
Defenders targeting nobody?

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#699] opened 2016-04-26 15:00 UTC
This might just be me not understanding the game mechanics, but several of my archers appear to be shooting at an off-screen ghost of some kind.  win7x64, 0.5.2 full.

![dq-offscreen-target](https://cloud.githubusercontent.com/assets/16719964/14822801/4f82dbf2-0bd0-11e6-8a7e-25d539b08820.png)

In fact, when I unpaused, I also witnessed the three knights in the bottom-right corner swinging wildly at nobody, too.  See screenshot at #701.

**Comment by larsiusprime** [comment] 2016-04-26 18:10
They should definitely not be firing at nobody! Archers will only shoot "at air" when they have no other choice -- they've already wound up a multi-arrow attack and started firing it, and suddenly they're out of targets. In that case they should keep shooting in the direction of the last shot on the off chance some target will wander into the path of the wild arrow. If they have valid in-range targets and they're not shooting at them, something is wrong.

**Comment by larsiusprime** [comment] 2016-04-26 18:10
Could you post a save file for this scenario so I can try to reproduce it?

**Comment by IBwWG** [comment] 2016-04-26 19:01
Yeah, no, as you can probably tell from the screenshot, there wasn't (couldn't have been) a target there.  Also for the knights...pretty bizarre.

Not sure if it was *exactly* with this, but probably, since it kept crashing near the end of the one battle, I don't think I made it much further than the save I started with.

[defender-shooting-nothing.zip](https://github.com/larsiusprime/tdrpg-bugs/files/237272/defender-shooting-nothing.zip)

**Comment by larsiusprime** [comment] 2016-04-28 20:57
Could you send me another save file post 0.5.7 next time you see this, which would have the starting layout stashed in your save as well? Thanks :)

**Comment by IBwWG** [comment] 2016-04-29 10:06
Still seeing it on 0.5.7.  Keep an eye on the healer just below Azra, even when no defender near by needs healing and there are no attackers near by either.

[defender-healer-targeting-nobody.zip](https://github.com/larsiusprime/tdrpg-bugs/files/242095/defender-healer-targeting-nobody.zip)

**Comment by IBwWG** [comment] 2016-04-29 10:07
Oh no...I'll have to redo that.  I went on to the next battle without thinking, then exported after that one.  Dang...

**Comment by IBwWG** [comment] 2016-04-29 10:10
Dang, now I can't get it to do it again.  Maybe they just reach further than I imagined or something.  Will keep an eye out.

**Comment by larsiusprime** [comment] 2016-04-29 15:08
One thing you can do, if it helps, is to turn on "hilight area effect attacks" in the graphics options, so you can be sure whether AOE attacks are behaving or not.

**Comment by IBwWG** [comment] 2016-05-05 19:58
I'm not sure what you mean exactly...so with the area attack on, what should I be able to tell differently re: targeting invisible targets?

Anyway, I just had this happen again, but with ice mages and healers.  All enemies have been dead for a few seconds, but they're still doing their area attack 3 (sleet?) over and over:

![dq-attacking-who](https://cloud.githubusercontent.com/assets/16719964/15055369/728628f0-130c-11e6-8d2c-166a24e0cfd0.png)

0.6.5, win7x64, HD mode@1704x960windowed

**Comment by IBwWG** [comment] 2016-05-05 20:02
![dq-attacking-who](https://cloud.githubusercontent.com/assets/16719964/15055440/ede190ac-130c-11e6-90c4-52f073b33bca.gif)

Although a few more seconds at 16X and the battle ended correctly.  :)

**Comment by larsiusprime** [comment] 2016-05-09 20:30
Likely just some enemy refusing to die because of some stupid reason. Weird.

**Comment by larsiusprime** [comment] 2016-05-27 20:04
Is it still happening?

**Comment by IBwWG** [comment] 2016-05-31 06:22
Not sure, will keep an eye out.

**Comment by IBwWG** [comment] 2016-05-31 08:15
I just tried the spiral-shaped level again and I could not reproduce the bug, with a very similar layout to the above, on 0.7.8, fullscreen.  I'll let you know if I see it again :)

**Comment by larsiusprime** [comment] 2016-06-07 17:35
Closing for now then :) Reopen if it happens again.

**Closed by larsiusprime** 2016-06-07 17:35 UTC
Labels: 1, bug, DQ CORE, Priority HIGH, Waiting
