### ISSUE TITLE
Expected Attribute Name

### ISSUE THREAD

**Issue by mikebell** [larsiusprime/tdrpg-bugs#1091] opened 2016-06-17 18:54 UTC
Windows 7, Steam version 2.0.1c

Finished the game and got the following:

![dqerror](https://cloud.githubusercontent.com/assets/242104/16161288/93fc686c-34c4-11e6-847d-c4f4e1846c2f.png)

Game then crashes, when I re-open it and load the save it give me a blank cutscene and quits again with "Null Object Reference" error. Loading it again brings me back into the game. I don't have the option for New Game+ either.

Here's my save incase it helps.
[borkedmebbe.zip](https://github.com/larsiusprime/tdrpg-bugs/files/321095/borkedmebbe.zip)

**Comment by ManDude** [comment] 2016-06-17 20:13
Was this AFTER or BEFORE the credits?

**Comment by mikebell** [comment] 2016-06-17 20:19
Before the credits. It went black where I assume there credits should be.

**Comment by ManDude** [comment] 2016-06-17 20:25
Alright, dupe of #1091.

**Closed by ManDude** 2016-06-17 20:25 UTC
